# -*- coding: utf-8 -*-
"""data extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZeDO9jms1kSAfgFsR3u_HqpZW1W7t4O
"""

# Import CARLA simulator Python API
import carla
# Used for sensor data buffering
import queue
# Numerical operations (arrays, matrices)
import numpy as np
# OpenCV for image processing and visualization
import cv2
# File and directory operations
import os
# Save/load data in JSON format
import json
# Create a client to connect to CARLA server (running locally on port 2000)
client = carla.Client('localhost', 2000)
# Set timeout (in seconds) for communication with the server
client.set_timeout(10.0)
# Get the current simulation world (map, actors, environment)
world = client.get_world()
# Retrieve current simulation settings
settings = world.get_settings()
# Enable synchronous mode:
# - Simulation runs step-by-step (frame-by-frame)
# - control when the world advances using world.tick()
settings.synchronous_mode = True
# Set fixed time step between frames (in seconds)
# 0.05 sec → 20 FPS simulation
settings.fixed_delta_seconds = 0.05
# Apply modified settings back to the world
world.apply_settings(settings)

# Get the blueprint library containing all available actors (vehicles, sensors, pedestrians, etc.)
blueprint_library = world.get_blueprint_library()
# Filter and select a specific vehicle blueprint 'filter' returns a list → [0] picks the first matching blueprint
vehicle_bp = blueprint_library.filter('vehicle.tesla.model3')[0]
# Get predefined spawn points from the map safe locations to place actors
spawn_point = world.get_map().get_spawn_points()[0]
# Spawn create the vehicle actor in the simulation at the chosen spawn point
vehicle = world.spawn_actor(vehicle_bp, spawn_point)

# Find an RGB camera sensor
rgb_bp = blueprint_library.find('sensor.camera.rgb')
# Set camera image width (in pixels)
rgb_bp.set_attribute('image_size_x', '800')
# Set camera image height (in pixels)
rgb_bp.set_attribute('image_size_y', '600')
# Spawn the RGB camera sensor in the simulation
rgb_cam = world.spawn_actor(
    # Blueprint defining camera properties
    rgb_bp,
    # Transform = position + orientation of the camera relative to the vehicle
    # x=1.5 → placed in front of vehicle
    # z=2.4 → height above ground (roof level)
    carla.Transform(carla.Location(x=1.5, z=2.4)),
    # Attach the camera to the vehicle (moves with it)
    attach_to=vehicle
    )

# Find (get) the blueprint for a semantic segmentation camera sensor this sensor assigns a class label to each pixel (road, car, pedestrian, etc.)
seg_bp = blueprint_library.find('sensor.camera.semantic_segmentation')
# Spawn the semantic segmentation camera in the simulation
seg_cam = world.spawn_actor(
    # Blueprint defining segmentation camera
    seg_bp,
    # Transform = position + orientation of the sensor (Usually same as RGB camera to align both outputs pixel-wise)
    transform,
    # Attach the segmentation camera to the vehicle ensures it moves with the vehicle
    attach_to=vehicle
    )

# Find (get) the blueprint for a depth camera sensor measures distance from the camera to objects in the scene
depth_bp = blueprint_library.find('sensor.camera.depth')
# Spawn the depth camera in the simulation
depth_cam = world.spawn_actor(
    # Blueprint defining depth sensor
    depth_bp,
    # Transform = position + orientation of the camera use same transform as RGB for pixel-perfect alignment
    transform,
    # Attach the depth camera to the vehicle ensures it moves together with the vehicle
    attach_to=vehicle
    )

# Find (get) the blueprint for a LiDAR sensor (ray-cast based) this simulates a real-world LiDAR by emitting rays and measuring distances
lidar_bp = blueprint_library.find('sensor.lidar.ray_cast')
# Set the maximum sensing range (in meters) LiDAR will detect objects up to 50 meters away
lidar_bp.set_attribute('range', '50')
# Set how many points are generated per second higher value → denser point cloud (more detail, more compute)
lidar_bp.set_attribute('points_per_second', '100000')
# Spawn the LiDAR sensor in the simulation
lidar = world.spawn_actor(
    # Blueprint defining LiDAR properties
    lidar_bp,
    # Transform = position of LiDAR relative to vehicle
    carla.Transform(carla.Location(z=2.5)),
    # Attach LiDAR to vehicle so it moves with it
    attach_to=vehicle
    )

# Find (get) the blueprint for an IMU sensor
# IMU = Inertial Measurement Unit (provides motion and orientation data)
imu_bp = blueprint_library.find('sensor.other.imu')
# Spawn the IMU sensor in the simulation
imu = world.spawn_actor(
    # Blueprint defining IMU sensor
    imu_bp,
    # Transform = position of IMU relative to vehicle
    # Empty transform → placed at vehicle's reference frame (center)
    carla.Transform(),
    # Attach IMU to the vehicle so it moves with it
    attach_to=vehicle
    )

# Find (get) the blueprint for a GNSS (GPS) sensor
# GNSS = Global Navigation Satellite System provides global position
gps_bp = blueprint_library.find('sensor.other.gnss')
# Spawn the GPS sensor in the simulation
gps = world.spawn_actor(
    # Blueprint defining GNSS sensor
    gps_bp,
    # Transform = position of sensor relative to vehicle
    # Empty transform → placed at vehicle's origin (center)
    carla.Transform(),
    # Attach GPS to the vehicle so it moves with it
    attach_to=vehicle
    )

# Find (get) the blueprint for an RGB camera this will be used to generate a Bird’s Eye View (top-down image)
bev_bp = blueprint_library.find('sensor.camera.rgb')
# Define the transform (position + orientation) for BEV camera
bev_transform = carla.Transform(
    # Place the camera high above the vehicle (z = 50 meters) this gives a wide top-down view of the surroundings
    carla.Location(z=50),
    # Rotate the camera to look straight down pitch = -90 → top-down (bird’s eye view)
    carla.Rotation(pitch=-90)
    )
# Spawn the BEV camera in the simulation
bev_cam = world.spawn_actor(
    # RGB camera blueprint
    bev_bp,
    # Top-down transform defined above
    bev_transform,
    # Attach the camera to the vehicle so it follows the vehicle while maintaining top view
    attach_to=vehicle
)

# Create queues to store incoming data from each sensor each queue acts as a buffer
seg_q = queue.Queue()
depth_q = queue.Queue()
lidar_q = queue.Queue()
imu_q = queue.Queue()
gps_q = queue.Queue()
# Register callback functions for each sensor .listen() starts the sensor and sends data to the given function
# For RGB camera → push each frame into rgb_q
rgb_cam.listen(rgb_q.put)
# For semantic segmentation camera → push frames into seg_q
seg_cam.listen(seg_q.put)
# For depth camera → push frames into depth_q
depth_cam.listen(depth_q.put)
# For LiDAR → push point cloud data into lidar_q
lidar.listen(lidar_q.put)
# For IMU → push motion data into imu_q
imu.listen(imu_q.put)
# For GPS → push location data into gps_q
gps.listen(gps_q.put)

# Loop to capture 4500 frames of synchronized sensor data
for frame in range(4500):
    # Advance the simulation by one step this ensures all sensors generate data for the same frame
    world.tick()
    # Retrieve data from each sensor queue
    # .get() blocks until data is available → ensures synchronization
    rgb = rgb_q.get()              # RGB camera image
    seg = seg_q.get()              # Semantic segmentation image
    depth = depth_q.get()          # Depth map image
    lidar_data = lidar_q.get()     # LiDAR point cloud data
    imu_data = imu_q.get()         # IMU readings (acceleration, gyro)
    gps_data = gps_q.get()         # GPS readings (lat, lon, altitude)
    # Save all sensor data for the current frame this function should handle storing images, point clouds, and metadata
    save_frame(frame, rgb, seg, depth, lidar_data, imu_data, gps_data)

def save_rgb(image, path):
    # Convert raw byte data from CARLA into a NumPy array (1D array of uint8)
    array = np.frombuffer(image.raw_data, dtype=np.uint8)
    # Reshape the array into image format: (height, width, 4 channels)
    # CARLA images are in BGRA format (Blue, Green, Red, Alpha)
    array = array.reshape((image.height, image.width, 4))
    # Save the image using OpenCV
    # array[:, :, :3] → remove alpha channel → keep BGR (first 3 channels)
    cv2.imwrite(path, array[:, :, :3])

def save_seg(image, path):
    # Convert the raw semantic segmentation image into a colored format
    image.convert(carla.ColorConverter.CityScapesPalette)
    # Save the converted image using the same function as RGB
    save_rgb(image, path)

def save_depth(image, path):
    # Convert the raw depth image into a logarithmic depth representation
    # Logarithmic scaling improves visibility of near and far objects
    image.convert(carla.ColorConverter.LogarithmicDepth)
    # Save the converted depth image using the RGB saving function
    save_rgb(image, path)

def save_imu(data, path):
    # Create a dictionary to store IMU readings in structured format
    imu_dict = {
        # Accelerometer data (linear acceleration in m/s² along x, y, z axes)
        "acc": [data.accelerometer.x, data.accelerometer.y, data.accelerometer.z],
        # Gyroscope data (angular velocity in rad/s along x, y, z axes)
        "gyro": [data.gyroscope.x, data.gyroscope.y, data.gyroscope.z]
        }
    # Save the IMU data as a JSON file
    # open(path, 'w') → open file in write mode
    # json.dump → write dictionary into file in JSON format
    json.dump(imu_dict, open(path, 'w'))

def save_gps(data, path):
    # Create a dictionary to store GPS (GNSS) readings
    gps_dict = {
        # Latitude → north-south position (in degrees)
        "lat": data.latitude,
        # Longitude → east-west position (in degrees)
        "lon": data.longitude,
        # Altitude → height above sea level (in meters)
        "alt": data.altitude
        }
    # Save the GPS data as a JSON file
    # open(path, 'w') → open file in write mode
    # json.dump → write dictionary into file in JSON format
    json.dump(gps_dict, open(path, 'w'))

# Get all actors in the world and filter only vehicles
actors = world.get_actors().filter('vehicle.*')
# Loop through each vehicle actor in the scene
for actor in actors:
    # Get the bounding box of the vehicle bounding box defines the 3D size and shape (length, width, height)
    bbox = actor.bounding_box
    # Get the transform (position + orientation) of the vehicle includes location (x, y, z) and rotation (pitch, yaw, roll)
    transform = actor.get_transform()

# Initialize an empty BEV (Bird’s Eye View) grid map 200 x 200 grid → represents spatial area around the vehicle
bev = np.zeros((200, 200))
# Loop through each LiDAR point
for point in points:
    # Extract x, y coordinates from point cloud multiply by 2 → scale real-world meters to grid resolution convert to integer indices for array indexing
    x, y = int(point[0] * 2), int(point[1] * 2)
    # Mark the grid cell as occupied (255 → white pixel) represents presence of an object at that location
    bev[x, y] = 255





