# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140V7R-l4uA_-T5ErzVfF4Aw60b1g9ZMy
"""

# Provides functions to interact with the operating system
import os

# Global configuration class for sensor setup, data processing, and model input settings
class GlobalConfig:
    # -----------------------------
    # temporal configuration
    # -----------------------------
    # number of past timesteps used as input sequence length
    seq_len = 1
    # number of image frames used can differ from overall sequence length
    img_seq_len = 1
    # number of LiDAR frames used can differ from images sequence length
    lidar_seq_len = 1
    # number of future timesteps waypoints the model predicts
    pred_len = 4
    # -----------------------------
    # image processing parameters
    # -----------------------------
    # scalling factor for image preprocessing
    scale = 1
    # image resolution after preprocessing -> (height, width)
    img_resolution = (160, 704)
    # width of processed image must be consistent with scale
    img_width = 320
    # -----------------------------
    # LiDAR processing parameters
    # -----------------------------
    # width of LiDAR Bird Eye View grid (numbef of cells along x-axis)
    lidar_resolution_width = 256
    # height of LiDAR Bird Eye View grid (number of cells along y-axis)
    lidar_resolution_height = 256
    # resolution of Bird Eye View grid (8 pixels represents 1 meter -> each pixel = 1 / 8 meter)
    pixels_per_meter = 8.0
    # -----------------------------
    # sensor calibration (Extrinsics)
    # -----------------------------
    # position of LiDAR sensor relative to vehicle origin in meter [x (forward), y (left/right), z(height)]
    lidar_pos = [1.3, 0.0, 2.5]
    # orientation of LiDAR sensor in degrees (Roll, Pitch, Yaw)
    # -90° yaw typically means LiDAR frame is rotated relative to vehicle frame
    lidar_rot = [0.0, 0.0, -90.0]
    # -----------------------------
    # Camera Configuration
    # -----------------------------
    # position of the camera in vehicle coordinate frame (in meters) [x (forward), y (left/right), z (height)]
    camera_pos = [1.3, 0.0, 2.3]
    # width of the camera image in pixels
    camera_width = 960
    # height of the camera image in pixels
    camera_height = 480
    # filed of view (FOV) of the camera in degrees determines how wide the camera can see
    camera_fov = 120
    # -----------------------------
    # Multi-Camera Setup (Extrinsics)
    # -----------------------------
    # orientation (Roll, Pitch, Yaw) of camera 0 facing strainght forward
    camera_rot_0 = [0.0, 0.0, 0.0]
    # orientation of camera 1
    # - rotated -60° yaw → looking towards left/front side
    camera_rot_1 = [0.0, 0.0, -60.0]
    # orientation of camera 2
    # - rotated +60° yaw → looking towards right/front side
    camera_rot_2 = [0.0, 0.0, 60.0]
    # -----------------------------
    # BEV (Bird’s Eye View) Settings
    # -----------------------------
    # width  of BEV output resolution (in pixels) used when upsampling BEV predictions or loss maps
    bev_resolution_width = 160
    # height of BEV output resolution (in pixels) ensure correct orientation if using non-square BEV maps
    bev_resolution_height = 160
    # -----------------------------
    # Target Point / Planning Input
    # -----------------------------
    # whether to encode target waypoint/goal as an image input (for planning models)
    use_target_point_image = True
    # whether to concatenate target point information into GRU (temporal model)
    gru_concat_target_point = True
    # -----------------------------
    # Data Augmentation
    # -----------------------------
    # enable data augmentation during training
    augment = True
    # inverse probability of applying augmentation
    # - actual augmentation probability = 1 - inverse_augementation_probability
    inv_augment_prob = 0.1
    # maximum random rotation (in degrees) applied during augmentation
    aug_max_rotation = 20
    # -----------------------------
    # Debugging & Visualization
    # -----------------------------
    # if true:
    # - Model inputs/outputs will be visualized
    # - Saved to disk (path defined elsewhere, e.g., SAVE_PATH)
    debug = False
    # frequency (in iterations) to save debug outputs during training
    train_debug_save_freq = 50
    # -----------------------------
    # Training Optimization
    # -----------------------------
    # if True:
    # - converts BatchNorm layers to synchronized BatchNorm
    # - useful for multi-GPU training
    sync_batch_norm = False
    # -----------------------------
    # Detection Threshold
    # -----------------------------
    # minimum confidence score required for a predicted bounding box, boxes below this threshold will be discarded
    bb_confidence_threshold = 0.3
    # -----------------------------
    # LiDAR Discretization (PointPillars specific) these parameters are used only if PointPillars-based encoding is enabled
    # -----------------------------
    # whether to use PointPillars representation for LiDAR processing
    #  If False → alternative LiDAR encoding is used
    use_point_pillars = False
    # Maximum number of LiDAR points considered per frame extra points are either truncated or randomly sampled
    max_lidar_points = 40000
    # -----------------------------
    # Spatial Range (in meters) defines the region of interest (ROI) in vehicle coordinate frame
    # -----------------------------
    #  X-axis range (left ↔ right or forward depending on convention)
    min_x = -16
    max_x = 16
    # Y-axis range (typically front-facing region of vehicle)
    min_y = -32
    max_y = 0
    # -----------------------------
    # Point Features
    # -----------------------------
    # number of input features per LiDAR point Example: [x, y, z, intensity, distance, etc.]
    num_input = 9
    # number of features (channels) in each layer of PointPillars feature extractor defines the network capacity for encoding pillar features
    num_features = [32, 32]
    # -----------------------------
    # Backbone Network
    # -----------------------------
    # specifies the main model architecture :
    # 'TransFuser' → fusion-based model combining camera + LiDAR features
    backbone = '/content/transFuser.py'
    # -----------------------------
    # CenterNet Detection Head Parameters
    # -----------------------------
    # number of discrete bins used to estimate object orientation (yaw angle)
    num_dir_bins = 12
    # whether to use mixed precision (FP16) training for faster computation and lower memory usage
    fp16_enabled = False
    # initial probability used to set bias in classification head helps stabilize early training for object detection
    center_net_bias_init_with_prob = 0.1
    # standard deviation for intializing weight in centernet layers
    center_net_normal_init_std = 0.001
    # number of top keypoints object centers selected during inference
    top_k_center_keypoints = 100
    # kernel size used in max pooling for local peak detection in heatmaps
    center_net_max_pooling_kernel = 3
    # number of feature channels in detection head
    channel = 64
    # -----------------------------
    # Bounding Box Adjustments
    # -----------------------------
    # scaling factor applied to bounding box width/height during data collection
    # used to correct dimensions (legacy fix, should ideally be removed in future datasets)
    bounding_box_divisor = 2.0
    # if predicted brake value exceeds this threshold: bounding box is visuallized with special "brake"
    draw_brake_threshhold = 0.5
    # -----------------------------
    # Waypoint Prediction (GRU)
    # -----------------------------
    # hidden state size of GRU used for sequential waypoint prediction
    gru_hidden_size = 64
    # -----------------------------
    # Semantic Classes Configuration
    # -----------------------------
    # total number of semantix classes used in the model
    num_class = 7
    # mapping of class index → color (BGR format) used for visualization (e.g., segmentation maps, BEV maps)
    classes = {
        0: [0, 0, 0],        # unlabeled / background
        1: [0, 0, 255],      # vehicle
        2: [128, 64, 128],   # road
        3: [255, 0, 0],      # red traffic light
        4: [0, 255, 0],      # pedestrian
        5: [157, 234, 50],   # road line / lane marking
        6: [255, 255, 255],  # sidewalk
    }
    # same class colors stored as a list (index = class id) useful for fast indexing during visualization
    classes_list = [
        [0, 0, 0],        # unlabeled
        [255, 0, 0],      # vehicle
        [128, 64, 128],   # road
        [0, 0, 255],      # red light
        [0, 255, 0],      # pedestrian
        [50, 234, 157],   # road line
        [255, 255, 255],  # sidewalk
    ]
    # -----------------------------
    # Label Converter (Dataset → Model Classes)
    # -----------------------------
    # Maps raw dataset labels (e.g., CARLA / segmentation IDs) to the reduced set of 7 classes used by the model
    converter = [
        0,  # unlabeled → ignore
        0,  # building → ignore
        0,  # fence → ignore
        0,  # other → ignore
        4,  # pedestrian → pedestrian
        0,  # pole → ignore
        5,  # road line → road line
        2,  # road → road
        6,  # sidewalk → sidewalk
        0,  # vegetation → ignore
        1,  # vehicle → vehicle
        0,  # wall → ignore
        0,  # traffic sign → ignore
        0,  # sky → ignore
        0,  # ground → ignore
        0,  # bridge → ignore
        0,  # rail track → ignore
        0,  # guard rail → ignore
        0,  # traffic light (generic) → ignore
        0,  # static → ignore
        0,  # dynamic → ignore
        0,  # water → ignore
        0,  # terrain → ignore
        3,  # red light → red light class
        3,  # yellow light → red light class (merged)
        0,  # green light → ignore
        0,  # stop sign → ignore
        5,  # stop line marking → road line
    ]

    # -----------------------------
    # Optimization Settings
    # -----------------------------
    # learning rate for optimizer controls how fast model updates weights
    learning_rate = 1e-4
    # Whether to train with multiple tasks (e.g., segmentation + depth estimation)
    multitask = True
    #  Loss scaling factor for segmentation task
    ls_seg = 1.0
    # Loss scaling factor for depth estimation task
    # Higher value → depth loss has more influence during training
    ls_depth = 10.0

    # -----------------------------
    # Convolutional Encoder Anchors
    # -----------------------------
    # Anchors define spatial grid locations used for feature extraction important for fusion models like TransFuser
    img_vert_anchors = 5
    # Number of vertical anchor divisions for image features
    # Number of horizontal anchor divisions for image features (+2 may account for padding or boundary handling)
    img_horz_anchors = 20 + 2
    #  Number of vertical anchor divisions for LiDAR BEV features
    lidar_vert_anchors = 8
    # Number of horizontal anchor divisions for LiDAR BEV features
    lidar_horz_anchors = 8
    # Total number of anchors (grid cells) for image and LiDAR
    img_anchors = img_vert_anchors * img_horz_anchors
    # Total image feature anchors
    lidar_anchors = lidar_vert_anchors * lidar_horz_anchors

    # -----------------------------
    # Loss Functions Configuration
    # -----------------------------
    detailed_losses = [
        'loss_wp',               # waypoint prediction loss
        'loss_bev',              # BEV (Bird’s Eye View) loss
        'loss_depth',            # depth estimation loss
        'loss_semantic',         # semantic segmentation loss
        'loss_center_heatmap',   # object center heatmap loss (CenterNet)
        'loss_wh',               # width & height regression loss (bounding boxes)
        'loss_offset',           # center offset regression loss
        'loss_yaw_class',        # yaw angle classification loss
        'loss_yaw_res',          # yaw residual regression loss
        'loss_velocity',         # object velocity prediction loss
        'loss_brake'             # brake prediction loss
    ]
    # Corresponding weights for each loss controls contribution of each task during training
    detailed_losses_weights = [
        1.0,  # waypoint
        1.0,  # BEV
        1.0,  # depth
        1.0,  # semantic
        0.2,  # center heatmap
        0.2,  # width/height
        0.2,  # offset
        0.2,  # yaw class
        0.2,  # yaw residual
        0.0,  # velocity (disabled)
        0.0   # brake (disabled)
    ]

    # -----------------------------
    # Feature Dimensions
    # -----------------------------
    # Number of feature channels output from perception backbone (image + LiDAR fusion)
    perception_output_features = 512
    # Number of channels used in BEV feature maps (feature pyramid)
    bev_features_chanels = 64
    # Upsampling factor for BEV features
    # Used to increase spatial resolution (e.g., for finer predictions)
    bev_upsample_factor = 2

    # -----------------------------
    # Deconvolution / Upsampling Layers
    # -----------------------------
    # Number of feature channels in the first deconvolution (upsampling) layer
    deconv_channel_num_1 = 128
    #  Number of channels in the second deconvolution layer
    deconv_channel_num_2 = 64
    # Number of channels in the third deconvolution layer
    deconv_channel_num_3 = 32
    # Upsampling factor after first deconvolution layer  (increases spatial resolution of feature map)
    deconv_scale_factor_1 = 8
    # Upsampling factor after second deconvolution layer
    deconv_scale_factor_2 = 4

    # -----------------------------
    # Temporal / Sensor Buffer
    # -----------------------------
    #  Maximum number of past GPS measurements stored used for trajectory estimation or smoothing
    gps_buffer_max_len = 100
    # Time per frame in CARLA simulator (in seconds)
    carla_frame_rate = 1.0 / 20.0
    # Frames per second of the CARLA simulation
    carla_fps = 20

    # -----------------------------
    # Post-processing (Detection)
    # -----------------------------
    #  IoU threshold for Non-Maximum Suppression (NMS)
    # Used to remove overlapping bounding box predictions
    iou_treshold_nms = 0.2

    # -----------------------------
    # Vehicle Control Parameters
    # -----------------------------
    #  Reduces steering magnitude when braking helps stabilize the vehicle
    steer_damping = 0.5

    # -----------------------------
    # Route Planning Parameters
    # -----------------------------
    # Minimum distance for waypoint selection
    route_planner_min_distance = 7.5
    #  Maximum distance for waypoint selection
    route_planner_max_distance = 50.0

    # -----------------------------
    # Action Execution / Control Frequency
    # -----------------------------
    #  Number of times each action is repeated (LiDAR runs at half the simulation frame rate)
    action_repeat = 2

    # -----------------------------
    # Stuck / Recovery Behavior
    # -----------------------------
    #  Number of frames after which the vehicle is considered "stuck" Adjusted by action_repeat
    stuck_threshold = 1100 / action_repeat
    # Number of frames the vehicle will move slowly forward (creep) to recover from being stuck
    creep_duration = 30 / action_repeat

    # -----------------------------
    # Safety Box (Collision Check Region)
    # -----------------------------
    # - Defines a 3D bounding region around the ego vehicle used for collision checking (e.g., LiDAR obstacle filtering)
    # Z-axis range (height) typically captures objects close to the ground (e.g., vehicles, obstacles)
    safety_box_z_min = -2.0
    safety_box_z_max = -1.05
    # Y-axis range (left/right) defines lateral safety zone around the vehicle
    safety_box_y_min = -3.0
    safety_box_y_max = 0.0
    #  X-axis range (forward/backward) defines front/rear safety region
    safety_box_x_min = -1.066
    safety_box_x_max = 1.066

    # -----------------------------
    # Ego Vehicle Dimensions (Half Extents)
    # -----------------------------
    # - These represent half-lengths of the ego vehicle in each axis used for collision detection, bounding boxes, and physics simulation
    # Half length of the vehicle along x-axis (front ↔ back)
    ego_extent_x = 2.4508416652679443
    # Half width of the vehicle along y-axis (left ↔ right)
    ego_extent_y = 1.0641621351242065
    # Half height of the vehicle along z-axis (bottom ↔ top)
    ego_extent_z = 0.7553732395172119

    # ---------------- GPT & Transformers Encoders Config ----------------
    # Embedding dimension (feature size per token) each token (image/LiDAR patch) is represented as a 512-dim vector
    n_embd = 512
    # Expansion factor for MLP inside transformer block hidden dimension = 4 × n_embd (e.g., 512 → 2048 → 512) controls model capacity
    block_exp = 4
    # Number of transformer blocks (depth of model)
    # More layers → more reasoning power (but more compute)
    n_layer = 4
    # Number of attention heads
    # Each head learns different relationships (spatial, semantic, cross-modal)
    n_head = 4
    # Number of fusion scales (multi-scale fusion levels)
    # Corresponds to transformer1, transformer2, transformer3, transformer4
    n_scale = 4
    #  Dropout applied to input embeddings (tokens + positional embeddings) helps prevent overfitting
    embd_pdrop = 0.1
    # Dropout applied to residual connections improves stability and generalization
    resid_pdrop = 0.1
    # Dropout applied inside attention weights
    # Prevents model from focusing too strongly on specific tokens
    attn_pdrop = 0.1

    # ---------------- Weight Intialization ----------------
    # Mean of normal distribution for initializing Linear layer weights
    gpt_linear_layer_init_mean = 0.0
    # Standard deviation for Linear layer initialization
    gpt_linear_layer_init_std = 0.02
    # Initial weight (gamma) for LayerNorm
    gpt_layer_norm_init_weight = 1.0

    # -----------------------------
    # PID Controller (Steering Control)
    # -----------------------------
    # - controls vehicle turning based on heading error
    # Proportional gain → reacts to current steering error
    turn_KP = 1.25
    # Integral gain → accumulates past errors (helps reduce steady-state error)
    turn_KI = 0.75
    # Derivative gain → reacts to rate of change of error (helps smooth control)
    turn_KD = 0.3
    # Buffer size for storing past errors (used in integral/derivative computation)
    turn_n = 20

    # -----------------------------
    # PID Controller (Speed / Throttle Control)
    # -----------------------------
    # - controls vehicle speed (acceleration & braking)
    # Proportional gain for speed error
    speed_KP = 5.0
    # Integral gain for accumulated speed error
    speed_KI = 0.5
    # Derivative gain for change in speed error
    speed_KD = 1.0
    # Buffer size for speed controller
    speed_n = 20

    # -----------------------------
    # Default / Safety Speed
    # -----------------------------
    # Default low speed used during creeping (e.g., when stuck)
    default_speed = 4.0

    # -----------------------------
    # Throttle & Brake Constraints
    # -----------------------------
    #  Maximum throttle value allowed (limits acceleration)
    max_throttle = 0.75
    # If current speed drops below this, braking is triggered
    brake_speed = 0.4
    #  Brake is applied if: current_speed > desired_speed * brake_ratio
    brake_ratio = 1.1
    # Maximum allowed change in speed input (prevents sudden acceleration changes)
    clip_delta = 0.25
    #  Hard upper limit on throttle output from controller
    clip_throttle = 0.75