# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyWDVmybNm6OPJP1HCBrga4soj4mQIZW
"""

!pip install ujson

# provides functions to interact with the operating system used for file paths, directory handling, etc.
import os

# OpenCV library for image processing used for reading, resizing, augmenting images
import cv2

# Ultra-fast JSON parser (faster than Python's built-in json) used for loading annotations / metadata
import ujson

# Image rotation utility from scikit-image used for data augmentation (rotating images / BEV maps)
from skimage.transform import rotate

# Numerical computing library used for array operations, matrix manipulation
import numpy as np

#  Base class for creating custom PyTorch datasets required for building data loaders
from torch.utils.data import Dataset

# Progress bar utility used to visualize loading/training progress
from tqdm import tqdm

# Provides access to system-specific parameters and functions often used for modifying path or runtime behavior
import sys

# Object-oriented file path handling Cleaner alternative to os.path
from pathlib import Path

# Imports global configuration class contains dataset paths, hyperparameters, etc.
from config import GlobalConfig

# Import transformation functions for converting between different coordinate frames
from utils import (
    # Converts coordinates from vehicle frame → virtual LiDAR frame
    get_vehicle_to_virtual_lidar_transform,
    # Converts vehicle coordinates → real LiDAR sensor coordinates
    get_vehicle_to_lidar_transform,
    # Converts LiDAR coordinates → vehicle coordinate system
    get_lidar_to_vehicle_transform,
    # Converts LiDAR 3D points → BEV (Bird’s Eye View) image space
    get_lidar_to_bevimage_transform
)

import zipfile

# Helper functions moved outside the class as they are called globally
def get_depth(data):
  """
  Computes the normalized depth
  """
  # Convert from (C, H, W) → (H, W, C) easier to process per-pixel RGB values
  data = np.transpose(data, (1, 2, 0))
  # Convert to float for numerical computation
  data = data.astype(np.float32)

  # ------------Decode Depth From RGB---------------
  # Convert RGB → single depth value
  # Formula : depth = R*256^2 + G*256 + B
  normalized = np.dot(data, [6536.0, 256.0, 1.0])
  # Normalize depth to range [0, 1] & Divide by max possible value (256^3 - 1)
  normalized /= (256 * 256 * 256 - 1)

  # ------------Convert to Meters-----------
  # CARLA depth range is typically 0-1000 meters
  in_meters = 1000 * normalized

  # --------------Clip depth range-----------
  # CARLA depth range is typically 0–1000 meters ≈ 0–50 meters (since 0.05 * 1000 ≈ 50m) removes far-away irrelent regions
  normalized = np.clip(normalized, a_min=0.0, a_max=0.05)

  # --------------------Rescale--------------
  # Scale back to [0, 1]
  normalized = normalized * 20.0
  # Output: (H, W) depth map normalized to [0, 1]
  return normalized

def get_waypoints(labels, len_labels):
  #  Ensure number of label frames matches expected sequence length
  assert(len(labels) == len_labels)
  # Dictionary to store trajectories for each object (car_id)
  num = len_labels
  waypoints = {}

  # ---------------Intialize with first time-------------
  # Unique ID of object (vehicle/pedestrian)
  for result in labels[0]:
    car_id = result["id"]
    #  Store:
    # ego_matrix → 4x4 transformation matrix (pose)
    # True → indicates object is present in this frame
    waypoints[car_id] = [[result['ego_matrix'], True]]

    # ----------Track same object in future frames----------
    # match object across frames using ID
    for i in range(1, num):
        for to_match in labels[i]:
            if to_match["id"] == car_id:
              # Append its pose in that frame
              waypoints[car_id].append([to_match["ego_matrix"], True])

    # --------------Identity Matrix For Padding---------------
    #  4x4 identity matrix → represents "no movement" or dummy pose
    Identity = list(list(row) for row in np.eye(4))

    # ----------------Handle mssing objects (Padding)----------
    # If object disappears in future frames:
        # - add dummy pose (identity matrix)
        # - False → indicates object is not present
    for k in waypoints.keys():
      while len(waypoints[k]) < num:
        waypoints[k].append([Identity, False])
  # Output : {car_id: [ego_matrix_t0, True], [ego_matrix_t1, False]}
  return waypoints

def transform_waypoints(waypoints):
  # Transformation from vehicle coordinate system → virtual LiDAR frame
  # Used to align all data into a common reference frame (BEV / LiDAR space)
  T = get_vehicle_to_virtual_lidar_transform()

  # Iterate over each tracked object (car_id)
  for k in waypoints.keys():
    # Get ego_matrix at current timestep (t0) this represents the reference frame (ego vehicle pose)
    vehicle_matrix = np.array(waypoints[k][0][0])
    # Compute inverse transformation & converts world coordinates → ego vehicle coordinates
    vehicle_matrix_inv = np.linalg.inv(vehicle_matrix)
    # Get pose of object at future timestep (t1, t2, ...)
    for i in range(1, len(waypoints[k])):
      matrix = np.array(waypoints[k][i][0])
    # Apply transformation chain:
    # 1. vehicle_matrix_inv → convert to ego-centric frame
    # 2. T → convert to virtual LiDAR / BEV frame
    waypoints[k][i][0] = T @ vehicle_matrix_inv @ matrix
  # Output:
  return waypoints

def align(lidar_0, measurements_0, measurements_1, degree=0):

  # -----------Get Ego Poses----------------
  # Ego vehicle pose at time t0 and t1 (4x4 transformation matrices)
  matrix_0 = measurements_0['ego_matrix']
  matrix_1 = measurements_1['ego_matrix']
  matrix_0 = np.array(matrix_0)
  matrix_1 = np.array(matrix_1)

  # ---------Sensor Transforms---------------
  # Transform from LiDAR frame → vehicle frame
  Tr_lidar_to_vehicle = get_lidar_to_vehicle_transform()
  # Tr_lidar_to_vehicle = get_lidar_to_vehicle_transform()
  Tr_vehicle_to_lidar = get_vehicle_to_lidar_transform()

  # ------------Compute Relative Transform------------
  # Full chain: LiDAR_t0 → Vehicle_t0 → World → Vehicle_t1 → LiDAR_t1
  transform_0_to_1 = (Tr_vehicle_to_lidar @ np.linalg.inv(matrix_1) @ matrix_0 @ Tr_lidar_to_vehicle)

  # -------------- Data Augmentation (Rotation)-----------
  # Rotation matrix around Z-axis (BEV rotation)
  rad = np.deg2rad(degree)
  degree_matrix = np.array([[np.cos(rad),  np.sin(rad), 0, 0],[-np.sin(rad), np.cos(rad), 0, 0],[0,0,1,0],[0,0,0,1]])
  # apply augementation rotation on top of alignment
  transform_0_to_1 = degree_matrix @ transform_0_to_1

  # ------------Prepare Point Cloud-------------
  # Convert to homogeneous coordinates (x, y, z, 1)
  lidar = lidar_0.copy()
  lidar[:, -1] = 1.0

  # -----------Fix Cooridates Covention----------
  # Flip Y-axis (undo earlier dataset convention)
  lidar[:, 1] *= -1.0

  # ------------Apply transformation------------
  # Transform all points from t0 → t1 frame
  lidar = transform_0_to_1 @ lidar.T
  lidar = lidar.T

  # -------------Restore Original format----------
  # Restore intensity channel
  lidar[:, -1] = lidar_0[:, -1]
  # flip Y-axis back to dataset convention
  lidar[:, 1] *= -1
  # Output: LiDAR points aligned to frame t1
  return lidar

def lidar_to_histogram_features(lidar):
  """
  Convert LiDAR point cloud into 2-bin histogram over 256x256 grid
  """
  def splat_points(point_cloud):
    # ---------------- Grid Configuration----------------
    # Resolution: 8 pixels = 1 meter
    pixels_per_meter = 8
    # Max number of points allowed per grid cell (clipping threshold)
    hist_max_per_pixel = 5
    # Range in X direction (left-right): -16m to +16m
    x_meters_max = 16
    # Range in Y direction (forward): 0 to 32m (front of vehicle)
    y_meters_max = 32

    # ---------------- Define grid bins ----------------
    # Divide X range into bins (grid cells)
    xbins = np.linspace(-x_meters_max, x_meters_max, 32 * pixels_per_meter + 1)
    #  Divide Y range into bins (only front region)
    ybins = np.linspace(-y_meters_max, 0, 32 * pixels_per_meter + 1)

    # ---------------- Histogram Creation----------------
    # Count number of points falling into each grid cell
    hist = np.histogramdd(point_cloud[..., :2], bins=(xbins, ybins))[0]

    # ----------------Clip values----------------
    # Limit max count per cell (avoid extreme density values)
    hist[hist > hist_max_per_pixel] = hist_max_per_pixel

    # ---------------- Normalize ----------------
    # Normalize values to [0, 1]
    overhead_splat = hist / hist_max_per_pixel
    # output
    return overhead_splat

  # ---------------- Split by height----------------
  # Points close to ground (road / ground surface)
  below = lidar[lidar[..., 2] <= -2.3]
  # Points above ground (vehicles, obstacles, structures)
  above = lidar[lidar[..., 2] > -2.3]

  # ---------------- Create features----------------
  # Ground-level density map
  below_features = splat_points(below)
  # Object-level density map
  above_features = splat_points(above)

  # ---------------- Stack channels----------------
  # Create 2-channel BEV:
  # Channel 0 → objects
  # Channel 1 → ground
  features = np.stack([above_features, below_features], axis=-1)

  # ---------------- Format for CNN ----------------
  # Convert (H, W, C) → (C, H, W)
  features = np.transpose(features, (2, 0, 1)).astype(np.float32)
  # Rotate grid to align with model coordinate system
  features = np.rot90(features, -1, axes=(1, 2)).copy()
  # Output shape: (2, 256, 256)
  return features

def get_bbox_label(bbox, rad=0):
  # ---------------- Input Format ----------------
  # bbox contains:
  # [dz, dx, dy, x, y, z, yaw, speed, brake]
  # dz, dx, dy → object dimensions
  # x, y, z → object position (in LiDAR / world frame)
  # yaw → orientation
  # speed, brake → additional attributes
  # Ignore z for BEV (top-down view)
  dz, dx, dy, x, y, z, yaw, speed, brake = bbox

  # ---------------- Grid Scale----------------
  # Convert real-world meters → pixel units
  pixels_per_meter = 8

  # ---------------- Data Augmentation (Rotation) ----------------
  # Rotation matrix (Z-axis) for augmentation in BEV
  degree_matrix = np.array([
      [np.cos(rad),  np.sin(rad), 0],
      [-np.sin(rad), np.cos(rad), 0],
      [0,            0,           1]
  ])

  # ---------------- Transfrom to BEV image space----------------
  # Combine : LiDAR -> BEV grid transfrom + rotation augmentation
  T = get_lidar_to_bevimage_transform() @ degree_matrix
  # Convert position → homogeneous coordinates (x, y, 1)
  position = np.array([x, y, 1.0]).reshape([3, 1])
  # Transform LiDAR coordinates → BEV pixel coordinates
  position = T @ position

  # ---------------- Clip To Image Bouds ----------------
  # Ensure coordinates lie inside BEV image (256×256)
  position = np.clip(position, 0., 255.)
  # Extract pixel coordinates
  x, y = position[:2, 0]

  # ---------------- Create BBOX In BEV----------------
  # Format: [center_x, center_y, width, height, yaw, speed, brake]
  # Notes:
  # dy -> width (left - right)
  # dx -> height (forward direction)
  bbox = np.array([x,y, dy * pixels_per_meter,dx * pixels_per_meter,
                   0,  # placeholder for yaw
                   0,  # placeholder for speed
                   0   # placeholder for brake
                   ])

  # ---------------- Add Attributes ----------------
  # Adjust orientation with augmentation rotation
  bbox[4] = yaw + rad
  # Object speed
  bbox[5] = speed
  # Brake state useful for behavior prediction
  bbox[6] = brake
  #  Output shape: (7,) -> [x, y, w, h, yaw, speed, brake]
  return bbox

def parse_labels(labels, rad=0):
  # Dictionary to store valid bounding boxes
  # Key → object ID
  # Value → processed BEV bbox
  bboxes = {}

  # iterate over all objects in curren frame
  for result in labels:
    # Number of LiDAR points inside this object used to filter weak / noisy detections
    num_points = result['num_points']
    # ---------------- Bulid Raw BBOX ----------------
    # Combine all properties into one list
    bbox = (
        result['extent'] +      # object size (dz, dx, dy)
        result['position'] +    # object position (x, y, z)
        [result['yaw'], result['speed'], result['brake']]
        )

    # ---------------- Convert to BEV format----------------
    # Convert 3D bbox -> 2D BEV bbox also applies augementation (rotation)
    bbox = get_bbox_label(bbox, rad)

    # ---------------- Filter invalid objects----------------
    # Skip:
    # - noisy objects & objects outside field of view
    if (
        num_points <= 1 or          # too few LiDAR points → unreliable detection
        bbox[0] <= 0.0 or           # x outside BEV image
        bbox[0] >= 255.0 or
        bbox[1] <= 0.0 or           # y outside BEV image
        bbox[1] >= 255.0
        ):
      continue

    # ---------------- Store valid BBOX----------------
    # Save bbox with object ID
    bboxes[result['id']] = bbox
  return bboxes

def crop_image_cv2(image, crop=(128, 640), channelFirst=False):
  """
  Scale and crop an image, returning optionally channels-first numpy array.
  """
  # get original image dimensions (H, W, C)
  width = image.shape[1]
  height = image.shape[0]
  # Desired crop size (height, width)
  crop_h, crop_w = crop

  # ---------------- Compute Centre Crop ----------------
  # Vertical starting point (centered)
  start_y = height // 2 - crop_h // 2
  # Horizontal starting point (centered)
  start_x = width // 2 - crop_w // 2

  # ---------------- Apply Crop----------------
  # Extract center region of image
  cropped_image = image[start_y:start_y + crop_h,start_x:start_x + crop_w]

  # ---------------- Format for model ----------------
  # Convert from (H, W, C) -> (C, H, W) required for PyTorch models
  if channelFirst:
    cropped_image = np.transpose(cropped_image, (2, 0, 1))
  return cropped_image

def load_crop_bev_npy(bev_array, degree):
  """
  Load and crop a BEV image & Crop depends on augmentation angle.
  """
  # ---------------- Grid settings----------------
  # Resolution: 5 pixels = 1 meter
  PIXELS_PER_METER_FOR_BEV = 5
  # Final crop size → 32 meters × 32 meters → (160 × 160 pixels)
  PIXLES = 32 * PIXELS_PER_METER_FOR_BEV

  # ---------------- Crop Region----------------
  # Center crop horizontally
  start_x = 250 - PIXLES // 2
  # Crop forward region front of vehicle
  start_y = 250 - PIXLES

  # ---------------- Format Conversion----------------
  # Convert (C, H, W) → (H, W, C)
  bev_array = np.moveaxis(bev_array, 0, -1).astype(np.float32)

  # ---------------- Align LiDAR offset ----------------
  # Shift BEV upward by 7 pixels
  # Reason: LiDAR is slightly offset (+1.3m in x direction) aligns BEV center with vehicle position
  bev_shift = np.zeros_like(bev_array)
  bev_shift[7:] = bev_array[:-7]

  # ---------------- Rotation Augmentaion ----------------
  # Rotate BEV for data augmentation
  bev_shift = rotate(bev_shift, degree)

  # ---------------- Crop Final Region----------------
  # Extract 32m × 32m region in front of vehicle
  cropped_image = bev_shift[start_y:start_y + PIXLES,start_x:start_x + PIXLES]

  # ---------------- Channel Format ----------------
  # Convert back (H, W, C) → (C, H, W)
  cropped_image = np.moveaxis(cropped_image, -1, 0)

  # --------------- Class Channels Processing ----------------
  # - predict others so append 0 to the first channel
  # creates multi-class representation:  channel 0 → background, channel 1 → class 1, channel 2 → combined classes
  cropped_image = np.concatenate((
      np.zeros_like(cropped_image[:1]),             # background channel
      cropped_image[:1],                            # first class
      cropped_image[:1] + cropped_image[1:2]        # combined class
  ), axis=0)

  # ---------------- Final labels map----------------
  #  Convert multi-channel → single-channel class map each pixel gets class index
  cropped_image = np.argmax(cropped_image, axis=0)
  # Output shape : (H, W) each pixel = class label
  return cropped_image

def draw_target_point(target_point, color=(255, 255, 255)):
  # Create empty BEV image (grayscale) size : 256 * 256 grid
  image = np.zeros((256, 256), dtype=np.uint8)
  # Copy to avoid modifying original data
  target_point = target_point.copy()

  # ---------------- Convert To LiDAR Coordinate ----------------
  # Shift Y to account for LiDAR offset (sensor not exactly at vehicle center)
  target_point[1] += 1.3

  # ---------------- Meters -> Pixels ----------------
  # Scale: 1 meter = 8 pixels
  point = target_point * 8.0

  # ---------------- Axis Conversion----------------
  # Flip Y-axis (LiDAR → image coordinate system)
  point[1] *= -1
  # Convert to image origin (top-left corner)
  point[1] = 256 - point[1]

  # ---------------- Centre Alignment----------------
  # Shift X so that ego vehicle is centered horizontally
  point[0] += 128

  # ----------------Format Fix ----------------
  # Convert to integer pixel coordinates
  point = point.astype(np.int32)
  # Ensure point lies inside image bounds
  point = np.clip(point, 0, 256)

  # ---------------- Draw Target Point----------------
  # Draw circle at target location
  cv2.circle(image, tuple(point), radius=5, color=color, thickness=3)

  # ---------------- Format For Model ----------------
  # Convert to (C, H, W)
  image = image.reshape(1, 256, 256)
  # Normalize to [0, 1]
  return image.astype(np.float32) / 255.0

def decode_pil_to_npy(img):
  # Define output:
  # 15 channels → encoded semantic BEV
  # width, height taken from input image
  (channels, width, height) = (15, img.shape[1], img.shape[2])
  # Intialize empty  multi-channel BEV tensor
  bev_array = np.zeros((channels, height, width), dtype=np.float32)

  # ----------Bit Decoding-----------
  # Select bit position from image
  for ix in range(5):
    # extract bit from image:
    # - img is encoded using bitmask
    # - each bit correspond to a class /channel
    # Store into 3 different channels groups :
    # ix -> first group
    # ix+5 -> second group
    # ix+10 -> third group
    bev_array[[ix, ix+5, ix+10]] = (img & (1 << ix)) >> ix
  # ------------- Select Channels------------
  # Return only specific channels (10 & 11) likely slected classes (e.g: road + obstacles)
  return bev_array[10:12]

class CARLA_Data(Dataset):
    def __init__(self, root, config: GlobalConfig, routeKey=None, load_raw_lidar=False, max_points=10000):
        # ---------------- Sequence Settigs ----------------
        # Number of past frames used as input (temporal context)
        self.seq_len = np.array(config.seq_len)
        # Number of future steps to predict (trajectory / planning)
        self.pred_len = np.array(config.pred_len)

        # ---------------- Image Settings ----------------
        #  Image height and width (resolution)
        self.img_resolution = np.array(config.img_resolution)
        # Image width (sometimes used separately for scaling/cropping)
        self.img_width = np.array(config.img_width)
        # Converts data (e.g., segmentation labels) into uint8 format useful for memory efficiecy and comptibility
        self.converter = np.uint8(config.converter)

        # ---------------- Lists Settigs ----------------
        # If True → load raw point cloud
        # If False → load processed BEV representation
        self.load_raw_lidar = load_raw_lidar

        # Maximum number of LiDAR points to keep helps limit memory usage and standardize input size
        self.max_points = max_points

        # ---------------- Data Storage Lists ----------------
        # Stores image file paths or processed images
        self.images = []
        # Stores BEV (Bird’s Eye View) representations
        self.bevs = []
        # Stores depth maps (from simulator or sensors)
        self.depths = []
        # Stores semantic segmentation labels (road, car, pedestrian, etc.)
        self.semantics = []
        # Stores LiDAR data (raw point cloud or BEV)
        self.lidars = []
        # Stores target labels (e.g., waypoints, control commands)
        self.labels = []
        # Stores additional data: speed, steering, throttle, GPS / pose
        self.measurements = []

        # ---------------- Load All Routes----------------
        # each route ~= one driving episode (like a video sequence) get all route folders inside dataset root
        # Changed hardcoded path to use `root` argument
        routes = sorted(os.listdir(root))

        # ---------------- Filter Routes ----------------
        # Optional Filtering : keep routes that match a specific key (e.g., "Town01", "train", etc.)
        if routeKey is not None:
          routes = [x for x in routes if routeKey in x]

        # ---------------- Convert To Absolute Paths ----------------
        # Convert relative route names → full directory paths
        routes = [os.path.join(root, x) for x in routes]

        # ---------------- Iterate Over Routes ----------------
        # tqdm → progress bar for dataset loading
        for route_dir_str in tqdm(routes, file=sys.stdout):
          # Convert string path → Path object (cleaner handling)
          route_dir = Path(route_dir_str)
          # Total number of frames in this route Using LiDAR folder as reference (all modalities aligned)
          num_seq = len(os.listdir(route_dir / "lidar"))

        # ---------------- SLIDING WINDOW OVER SEQUENCE ----------------
        # ignore first 2 and last few frames (boundary safety)
        for seq in range(2, num_seq - self.pred_len - self.seq_len - 2):
          # ---------------- LOAD CURRENT FRAME DATA ----------------
          # RGB image at current timestep
          image = '/content/drive/MyDrive/rgb.zip'
          # BEV (Bird’s Eye View) representation
          bev = '/content/drive/MyDrive/topdown.zip'
          # Depth Map
          depth = '/content/drive/MyDrive/depth.zip'
          # Semantic segmentation ground truth
          semantic = '/content/drive/MyDrive/semantics.zip'
          # LiDAR data (point cloud or BEV representation)
          lidar = '/content/drive/MyDrive/lidar.zip'
          # Vehicle measurements: speed, steering, throttle, position, etc.
          measurement = '/content/drive/MyDrive/measurements.zip'

          # ---------------- Load Future Labels ----------------
          # Stores future trajectory / waypoint labels
          label = []
          # Collect labels for: past frame (seq_len), future frames (pred_len) this sequence -> future prediction
          for idx in range(self.seq_len + self.pred_len):
            label.append(
                route_dir / "label_raw" / ("%04d.json" % (seq + idx))
            )

          # Store path to RGB image for this timestep
          self.images.append(image)
          # Store BEV (top-down / bird’s-eye view) representation
          self.bevs.append(bev)
          # Store depth map (distance information per pixel)
          self.depths.append(depth)
          # Store semantic segmentation label (pixel-wise classes)
          self.semantics.append(semantic)
          # Store LiDAR data (point cloud or BEV grid)
          self.lidars.append(lidar)
          # Store sequence of labels (future waypoints / trajectory info)
          self.labels.append(label)
          # Store vehicle measurements (speed, steering, throttle, etc.)
          self.measurements.append(measurement)
          self.images = np.array(self.images).astype(np.string_)

          # Convert list of image paths → NumPy array of strings ensures consistent format and faster indexing
          # Store BEV file paths as NumPy string array
          self.bevs = np.array(self.bevs).astype(np.string_)
          # Store depth map paths
          self.depths = np.array(self.depths).astype(np.string_)
          # Store semantic segmentation label paths
          self.semantics = np.array(self.semantics).astype(np.string_)
          # Store LiDAR file paths
          self.lidars = np.array(self.lidars).astype(np.string_)
          # Store label paths (sequence of JSON files)
          self.labels = np.array(self.labels).astype(np.string_)
          # Store measurement file paths (speed, control, etc.)
          self.measurements = np.array(self.measurements).astype(np.string_)

    def __len__(self):
      """Returns the length of the dataset."""
      # Dataset size = number of samples all list (images, lidars, labels etc) have same length
      return self.lidars.shape[0]

    def __getitem__(self, index):
      """Returns the item at index"""
      # Disable OpenCV threading (PyTorch DataLoader already uses multiprocessing)
      cv2.setNumThreads(0)
      # Dictionary to store all modalities for this sample
      data = {}

      # ------------RGB Image Processing--------------
      rgb_image = cv2.imread(str(self.images[index], encoding='utf-8'), cv2.IMREAD_COLOR)
      rgb_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2RGB)
      data['rgb'] = crop_image_cv2(rgb_image, crop=self.img_resolution, channelFirst=True)

      # ----------- BEV (Top Down View)----------------
      bev_array = cv2.imread(str(self.bevs[index], encoding='utf-8'), cv2.IMREAD_UNCHANGED)
      bev_array = cv2.cvtColor(bev_array, cv2.COLOR_BGR2RGB)
      bev_array = np.moveaxis(bev_array, -1, 0)
      loaded_bevs = decode_pil_to_npy(bev_array).astype(np.uint8)
      data['bev'] = load_crop_bev_npy(loaded_bevs, degree=0)

      # ------------ Depth Map------------------------
      depth_image = cv2.imread(str(self.depths[index], encoding='utf-8'), cv2.IMREAD_COLOR)
      depth_image = cv2.cvtColor(depth_image, cv2.COLOR_BGR2RGB)
      data['depth'] = get_depth(crop_image_cv2(depth_image, crop=self.img_resolution, channelFirst=True))

      # ------------ Semantic Segmentation-------------
      semantic_image = cv2.imread(str(self.semantics[index], encoding='utf-8'), cv2.IMREAD_UNCHANGED)
      data['semantic'] = self.converter[crop_image_cv2(semantic_image, crop=self.img_resolution)]

      # ------------- Vehicle Measurements------------
      with open(str(self.measurements[index], encoding='utf-8'), 'r') as f1:
        measurements = ujson.load(f1)
      for k in ['speed', 'x_command', 'y_command']:
        data[k] = measurements[k]

      # -------------- Target Point-----------------
      ego_theta = measurements['theta']
      ego_x = measurements['x']
      ego_y = measurements['y']
      R = np.array([[np.cos(np.pi/2+ego_theta), -np.sin(np.pi/2+ego_theta)],
       [np.sin(np.pi/2+ego_theta),  np.cos(np.pi/2+ego_theta)]])
      # Fixed x_command and y_command to use measurements dict
      local_command_point = np.array([measurements['x_command']-ego_x, measurements['y_command']-ego_y])
      local_command_point = R.T.dot(local_command_point)
      data['target_point'] = local_command_point
      data['target_point_image'] = draw_target_point(local_command_point)

      # ----------- Load Point Cloud-------------
      # Load LiDAR point cloud from file : Format -> (N, 4) -> [X, Y, Z, Intensity]
      # [1] selects actual point cloud data
      lidars_pc = np.load(str(self.lidars[index], encoding='utf-8'), allow_pickle=True)[1]

      # ------------ Raw LiDAR Processing-----------
      if self.load_raw_lidar:
        # copy LiDAR point cloud
        raw_pc = lidars_pc
        # swap X and Y axis convert coordinate system
        raw_pc = raw_pc[:, [1, 0, 2]]

        # ----------------- Filter Region Of Interest (ROI)-----------
        # this keep only relevant points for driving : front facing + limited width + above ground
        raw_pc = raw_pc[(raw_pc[...,0]) & # keep points in front of vehicle
                        (raw_pc[..., 0] < 64) &  # max forward distance = 64 meters
                        (np.abs(raw_pc[..., 1]) < 30) & # left-right range = ±30 meters
                        (raw_pc[..., 2] > -2.4)         # remove ground / very low points
                        ]

        # ------------- Fixed Size Padding-------------
        # Create fixed-size array (important for batching)
        raw_pc_pad = np.zeros((self.max_points, 3), dtype=np.float32)
        # Number of valid point (capped at max_points)
        num_raw_lidar_points = min(self.max_points, raw_pc.shape[0])
        # copy valid points into padded array remaining rows stay zeros (padding)
        raw_pc_pad[:num_raw_lidar_points, :] = raw_pc[:num_raw_lidar_points, :]

        # ------------------Store In Data-----------------
        # final raw LiDAR tensor
        data['raw_lidar'] = raw_pc_pad
        # number of actual points
        data['num_raw_lidar_points'] = num_raw_lidar_points
        # flip y-axis of LiDAR point converts corrdinate system to match BEV / image convention
        lidars_pc[:,1] *= -1
        # convert raw LiDAR point cloud -> BEV histogram features output is 2D grid (multi-channel) reprentation
        data['lidar'] = lidar_to_histogram_features(lidars_pc)
        # List to store label data for multiple timesteps (past + future)
        labels = []
        # Load label JSON files for : past frames(seq_len), future frames(pred_len)
        for i in range(self.seq_len + self.pred_len):
          # Each file contain object states
          with open(str(self.labels[index][i], encoding = "utf-8"), 'r') as f2:
            labels_i = ujson.load(f2)
          labels.append(labels_i)

        # -------------Ego Vehicle ID----------------
        # First object in label file corresponds to ego vehicle store its unique ID for tracking across frames
        ego_id = labels[0][0]['id']

        # ---------------Object Bounding Boxes (current Frame)------
        # Extract bounding boxes from current frame (timestep t)
        bboxes = parse_labels(labels[0])
        # Convert dictionary → array of bounding boxes
        label = np.array(list(bboxes.values()))
        # Create fixed-size tensor (max 20 objects)
        label_pad = np.zeros((20, 7), dtype=np.float32)
        # Copy actual boxes into padded array
        if label.shape[0] > 0:
          label_pad[:label.shape[0], :] = label
        # Final bounding box tensor for model
        data['label'] = label_pad

        # ---------Future Waypoints------------
        # Extract trajectories starting from last input frame includes future position of all objects
        waypoints = get_waypoints(labels[self.seq_len-1:], self.pred_len + 1)
        # Convert  waypoints to consistent coordinate frame (ego-centric)
        waypoints = transform_waypoints(waypoints)

        # -----------Ego Trajectory--------------
        # Extract ego vehicle positions from transformation matrices
        # - [:2, 3] → x, y position (translation component)
        # - [1:] → skip current frame, keep only future waypoints
        ego_waypoints = np.array([x[0][:2, 3] for x in waypoints[ego_id][1:]])
        # Represents future trajectory of ego vehicle
        data['ego_waypoint'] = ego_waypoints

        # ---------Output--------
        return data

