# -*- coding: utf-8 -*-
"""e2e_cam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qp0Ufh9Sv1jofrhsiWQ5V6VH6Qc_U-f1
"""

# Import OpenCV library for image processing tasks
import cv2
# Import tqdm for displaying progress bars in loops
import tqdm
# Import NumPy for numerical operations and array handling
import numpy as np
# Import zoom function for resizing arrays/images
from scipy.ndimage import zoom
# Import matplotlib for plotting and visualizing images/graphs
import matplotlib.pyplot as plt
# Import type hints for better code readability and structure
from typing import Callable, List, Tuple, Any
# Import OrderedDict which remembers the order of inserted items
from collections import OrderedDict
# Import PyTorch library for building and modifying neural networks
import torch

# Function to recursively search and replace a layer in a model
def replace_layer_recursive(model, old_layer, new_layer):
    # Loop through all submodules (layers) of the model
    for name, layer in model._modules.items():
        # Check if the current layer matches the layer we want to replace
        if layer == old_layer:
            # Replace the old layer with the new layer
            model._modules[name] = new_layer
            # Return True to indicate replacement was successful
            return True
        # If not found, recursively search inside the current layer
        elif replace_layer_recursive(layer, old_layer, new_layer):
            # If replacement happened in a nested layer, return True
            return True
    # If the layer is not found anywhere in the model, return False
    return False

class ActivationsAndGradients:
    """ Class for extracting activations and registering gradients from targeted intermediate layers """
    def __init__(self, model, target_layers, reshape_transform):
        # Store the model
        self.model = model
        # List to store gradients from target layers
        self.gradients = []
        # List to store activations (outputs) from target layers
        self.activations = []
        # Optional function to reshape outputs (useful for models like ViT)
        self.reshape_transform = reshape_transform
        # Store hook handles so they can be removed later
        self.handles = []
        # Loop through each target layer where we want hooks
        for target_layer in target_layers:
            # Register a forward hook to save activations
            self.handles.append(target_layer.register_forward_hook(self.save_activation))
            # Register another forward hook to capture gradients
            self.handles.append(target_layer.register_forward_hook(self.save_gradient))

    # Function to save activations (forward outputs) from a layer
    def save_activation(self, module, input, output):
      # output of the layer is the activation
      activation = output
      # If a reshape function is provided (e.g., for transformer models), apply it to transform the activation into desired shape
      if self.reshape_transform is not None:
          activation = self.reshape_transform(activation)
      # Detach the activation from the computation graph (no gradients),move it to CPU (for storage/processing), and store it in the list
      self.activations.append(activation.cpu().detach())

    # function to save gradients during the backward pass
    def save_gradient(self, module, input, output):
      # check if the output tensor supports gradients (only tensors with requires_grad=True can have hooks)
      if not hasattr(output, "requires_grad") or not output.requires_grad:
        # if gradients are not tracked, exit the function
        return
      # define a function that will be called when gradients are computed this function captures and stores the gradient
      def _store_grad(grad):
        # apply reshape transformation if provided
        if self.reshape_transform is not None:
          grad = self.reshape_transform(grad)
          # Detach gradient from computation graph, move to CPU, and store it at the beginning of the list
          self.gradients = [grad.cpu().detach()] + self.gradients
      # Register the hook on the output tensor this ensures _store_grad is called during backpropagation
      output.register_hook(_store_grad)

    # Makes the class instance callable like a function
    def __call__(self, x):
      # Reset stored gradients before a new forward pass
      self.gradients = []
      # Reset stored activations before a new forward pass
      self.activations = []
      # Perform forward pass through the model with input x
      return self.model(x)

    # Function to remove all registered hooks
    def release(self):
      # Loop through all stored hook handles
      for handle in self.handles:
        # Remove each hook to free memory and avoid unwanted behavior
        handle.remove()

    # Function overlays the CAM (Class Activation Map) mask on the image as a heatmap.
    def show_cam_on_image(img: np.ndarray,mask: np.ndarray,use_rgb: bool = False,
                          colormap: int = cv2.COLORMAP_JET,image_weight: float = 0.5):
      # Convert mask (values 0–1) to 0–255 and apply a colormap (e.g., JET)
      heatmap = cv2.applyColorMap(np.uint8(255 * mask), colormap)
      # Convert heatmap to RGB if the input image is in RGB format
      if use_rgb:
          heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
      # Normalize heatmap to range [0, 1]
      heatmap = np.float32(heatmap) / 255
      # Ensure input image is normalized between [0, 1]
      if np.max(img) > 1:
          raise Exception("The input image should np.float32 in the range [0, 1]")
      # Ensure image_weight is valid (must be between 0 and 1)
      if image_weight < 0 or image_weight > 1:
          raise Exception(f"image_weight should be in the range [0, 1] Got: {image_weight}")
      # Blend heatmap with the original image
      # Final image = (1 - weight)*heatmap + weight*original image
      cam = (1 - image_weight) * heatmap + image_weight * img
      # Normalize the final combined image to [0, 1]
      cam = cam / np.max(cam)
      # Convert to 0–255 range and uint8 format for display or saving
      return np.uint8(255 * cam)

    def scale_cam_image(cam, target_size=None):
      # List to store processed CAM images
      result = []
      # Loop through each image in the CAM batch
      for img in cam:
          # Normalize image: shift values so minimum becomes 0
          img = img - np.min(img)
          # Scale values to range [0, 1] (avoid division by zero using small epsilon)
          img = img / (1e-7 + np.max(img))
          # If a target size is specified, resize the image
          if target_size is not None:
              # If image has more than 3 dimensions (e.g., 3D CAM or multi-channel)
              if len(img.shape) > 3:
                  # Resize using scipy zoom with computed scaling factors
                  img = zoom(np.float32(img),[(t_s / i_s) for i_s, t_s in zip(img.shape, target_size[::-1])])
              else:
                  # For normal 2D/3D images, use OpenCV resize
                  img = cv2.resize(np.float32(img), target_size)
          # Append processed image to result list
          result.append(img)
      # Convert list of images into a NumPy array of type float32
      result = np.float32(result)
      # Return the scaled CAM images
      return result

    def get_2d_projection(activation_batch):
      # Replace NaN values with 0 to avoid computation issues
      activation_batch[np.isnan(activation_batch)] = 0
      # List to store final 2D projections
      projections = []
      # Loop through each activation map in the batch
      for activations in activation_batch:
          # Reshape activations:
          # From (channels, height, width) → (height*width, channels)
          reshaped_activations = (activations).reshape(activations.shape[0], -1).transpose()
          # Center the data (subtract mean) before applying SVD this improves the quality of the projection
          reshaped_activations = reshaped_activations - reshaped_activations.mean(axis=0)
          # Perform Singular Value Decomposition (SVD)
          # U: left singular vectors
          # S: singular values
          # VT: right singular vectors (transposed)
          U, S, VT = np.linalg.svd(reshaped_activations, full_matrices=True)
          # Project data onto the first principal component (direction of maximum variance)
          projection = reshaped_activations @ VT[0, :]
          # Reshape back to spatial dimensions (height, width)
          projection = projection.reshape(activations.shape[1:])
          # Store the resulting 2D projection
          projections.append(projection)
      # Convert list to NumPy array with float32 precision
      return np.float32(projections)

# Base class for CAM (Class Activation Map) methods
class BaseCAM:
    def __init__(self, model: torch.nn.Module, target_layers: List[torch.nn.Module],
                 reshape_transform: Callable = None) -> None:
        # Store the PyTorch model
        self.model = model
        # Store the layers from which CAM will be computed
        self.target_layers = target_layers
        # Get the device (CPU/GPU) where the model is located this ensures all computations happen on the same device
        self.device = next(self.model.parameters()).device
        # Optional function to reshape activations (useful for non-CNN models like ViT)
        self.reshape_transform = reshape_transform
        # Initialize helper class to capture activations and gradients from the target layers during forward and backward passes
        self.activations_and_grads = ActivationsAndGradients(self.model, target_layers, reshape_transform)

    # Method to compute weights used in generating the CAM (Class Activation Map)
    def get_cam_weights(self, input_data: Any, target_layers: List[torch.nn.Module],
                        targets: List[torch.nn.Module], activations: torch.Tensor,
                        grads: torch.Tensor):
      # this method is intentionally left unimplemented in the base class
      # It is meant to be overridden in subclasses (e.g., GradCAM, ScoreCAM, etc.)
      # Raise an exception if this base method is called directly
      raise Exception("Not Implemented")

    # Function to compute the Class Activation Map (CAM) image
    def get_cam_image(self, input_data: Any, target_layer: torch.nn.Module,
                      targets: List[torch.nn.Module], activations: torch.Tensor,
                      grads: torch.Tensor, eigen_smooth: bool = False):
      # Compute weights for each channel using a CAM-specific method implemented in subclasses like Grad-CAM
      weights = self.get_cam_weights(input_data, target_layer, targets, activations, grads)
      # Handle 2D convolutional feature maps: (batch, channels, height, width)
      if len(activations.shape) == 4:
        # Expand weights to match activation dimensions and multiply weights shape: (batch, channels) → (batch, channels, 1, 1)
        weighted_activations = weights[:, :, None, None] * activations
      # Handle 3D convolutional feature maps: (batch, channels, depth, height, width)
      elif len(activations.shape) == 5:
        # Expand weights accordingly for 3D case weights shape: (batch, channels) → (batch, channels, 1, 1, 1)
        weighted_activations = weights[:, :, None, None, None] * activations
      else:
        # Raise error if activation shape is unexpected
        raise ValueError(f"Invalid activation shape. Get {len(activations.shape)}.")
      # Optionally apply eigenvalue-based smoothing (PCA-like projection)
      if eigen_smooth:
        # Reduce multi-channel map to 2D using projection (more stable visualization)
        cam = get_2d_projection(weighted_activations)
      else:
        # Standard CAM: sum across channels to get a 2D heatmap
        cam = weighted_activations.sum(axis=1)
      # Return the computed CAM
      return cam

    # Forward method to compute CAMs (Class Activation Maps)
    def forward(self, input_data: Any, targets: List[torch.nn.Module], eigen_smooth: bool = False, keys = []):
      # Run a forward pass through the model this also triggers hooks to store activations and gradients
      self.outputs = self.activations_and_grads(input_data)
      # Compute CAM for each target layer
      cam_per_layer = self.compute_cam_per_layer(input_data, targets, eigen_smooth, keys)
      # Return CAM results (possibly aggregated across layers)
      return cam_per_layer

    # Function to extract target spatial dimensions (width, height, or depth) from the input data (used later for resizing CAM outputs)
    def get_target_width_height(self, input: Any, key: str = '') -> Tuple[int, int]:
      # If input is a dictionary, extract the actual tensor using the given key
      if isinstance(input, dict):
        input_data = input.get(key, None)
      else:
          # Otherwise, assume input itself is the tensor
          input_data = input
      # Proceed only if input_data is valid
      if input_data is not None:
          # 2D image input (batch, channels, height, width)
          if len(input_data.shape) == 4:
              # Extract width and height from the last dimensions
              width, height = input_data.size(-1), input_data.size(-2)
              return width, height
          # 3D image input (batch, channels, depth, height, width)
          elif len(input_data.shape) == 5:
              # Extract depth, width, and height
              depth = input_data.size(-3)
              width = input_data.size(-1)
              height = input_data.size(-2)
              return depth, width, height
          else:
              # Raise error if input shape is not supported
              raise ValueError("Invalid input_data shape. Only 2D or 3D images are supported.")
      else:
          # Raise error if input_data is None (invalid or missing key)
          raise ValueError("Nan Input")

    # Function to compute CAM for each target layer
    def compute_cam_per_layer(self, input: Any, targets: List[torch.nn.Module], eigen_smooth: bool, keys = []):
      # Convert stored activations and gradients from tensors to NumPy arrays
      activations_list = [a.cpu().data.numpy() for a in self.activations_and_grads.activations]
      grads_list = [g.cpu().data.numpy() for g in self.activations_and_grads.gradients]
      # List to store CAM results for each target layer
      cam_per_target_layer = []
      # Loop over each target layer
      for i in range(len(self.target_layers)):
        # Get the current target layer
        target_layer = self.target_layers[i]
        # Initialize activations and gradients for this layer
        layer_activations = None
        layer_grads = None
        # Safely fetch activations if available
        if i < len(activations_list):
            layer_activations = activations_list[i]
        # Safely fetch gradients if available
        if i < len(grads_list):
            layer_grads = grads_list[i]
        # Compute CAM for this layer using activations and gradients
        cam = self.get_cam_image(input, target_layer, targets,layer_activations, layer_grads,eigen_smooth)
        # Apply ReLU (remove negative values)
        cam = np.maximum(cam, 0)
        # Get target size (width, height or depth) for resizing CAM
        target_size = self.get_target_width_height(input, keys[i])
        # Resize CAM to match input dimensions
        scaled = scale_cam_image(cam, target_size)
        # Add channel dimension (for consistency) and store result
        # shape becomes: (batch, 1, height, width)
        cam_per_target_layer.append(scaled[:, None, :])
      # Return list of CAMs (one per target layer)
      return cam_per_target_layer

    # Function to aggregate CAMs from multiple target layers
    def aggregate_multi_layers(self, cam_per_target_layer: np.ndarray):
      # Concatenate CAMs along the channel dimension
      cam_per_target_layer = np.concatenate(cam_per_target_layer, axis=1)
      # Apply ReLU to remove negative values
      cam_per_target_layer = np.maximum(cam_per_target_layer, 0)
      # Take mean across layers to get a single CAM per image
      result = np.mean(cam_per_target_layer, axis=1)
      # Normalize and scale the final CAM
      return scale_cam_image(result)

    # Make the class callable like a function
    def __call__(self, input_data: Any, targets: List[torch.nn.Module] = None,
                 eigen_smooth: bool = False, key: str = ''):
      # Simply call the forward method
      return self.forward(input_data, targets, eigen_smooth, key)


    # Destructor: automatically called when the object is deleted
    def __del__(self):
      # Release hooks to free memory and avoid side effects
      self.activations_and_grads.release()


    # Enter method for context manager (used with 'with' statement)
    def __enter__(self):
      # Return the current instance
      return self


    # Exit method for context manager
    def __exit__(self, exc_type, exc_value, exc_tb):
      # Always release hooks when exiting the context
      self.activations_and_grads.release()
      # Handle specific exception (IndexError) gracefully
      if isinstance(exc_value, IndexError):
        # Print error message instead of crashing
        print(f"An exception occurred in CAM with block: {exc_type}. Message: {exc_value}")
        # Return True to suppress the exception
        return True

class EigenCAM(BaseCAM):
    def __init__(self, model, target_layers, reshape_transform=None):
      # Initialize the parent BaseCAM class
      super(EigenCAM, self).__init__(model,target_layers,reshape_transform)
    # Override the method to compute CAM image
    def get_cam_image(self,input_data,target_layer,target_category,activations,grads,eigen_smooth):
      # Convert multi-channel activations into a single 2D heatmap using the first principal component
      return get_2d_projection(activations)

class AblationLayer(torch.nn.Module):
    def __init__(self):
        # Initialize the parent nn.Module
        super(AblationLayer, self).__init__()
    # Function to generate a binary "objectiveness" mask using SVD (EigenCAM idea)
    def objectiveness_mask_from_svd(self, activations, threshold=0.01):
        """
        Experimental method to decide which regions of the activation map are important (worth ablating) and which are not.
        """
        # Add batch dimension and compute 2D projection (EigenCAM)
        projection = get_2d_projection(activations[None, :])[0, :]
        # Take absolute values to focus on magnitude of importance
        projection = np.abs(projection)
        # Normalize: shift minimum to 0
        projection = projection - projection.min()
        # Normalize: scale to range [0, 1]
        projection = projection / projection.max()
        # Create binary mask: True (1) for important regions, False (0) for less important ones
        projection = projection > threshold
        # Return binary mask
        return projection

    # Function to decide which activation channels should be ablated
    def activations_to_be_ablated(self,activations,ratio_channels_to_ablate=1.0):
      """
      Experimental method to select important activation channels for ablation.
      Steps:
      - Generate a binary importance mask using SVD (EigenCAM idea)
      - Score each channel based on how much it overlaps with important regions
      - Select top channels (and optionally some low ones)
      """
      # If ratio is 1.0 → select ALL channels (no filtering)
      if ratio_channels_to_ablate == 1.0:
        self.indices = np.int32(range(activations.shape[0]))
        return self.indices
      # Generate binary mask of important spatial regions
      projection = self.objectiveness_mask_from_svd(activations)
      # List to store importance scores for each channel
      scores = []
      # Loop through each channel in activations
      for channel in activations:
        # Take absolute values (focus on magnitude)
        normalized = np.abs(channel)
        # Normalize channel values to [0, 1]
        normalized = normalized - normalized.min()
        normalized = normalized / np.max(normalized)
        # Compute score: Measures how much this channel aligns with important regions
        score = (projection * normalized).sum() / normalized.sum()
        # Store the score
        scores.append(score)
      # Convert scores list to NumPy array
      scores = np.float32(scores)
      # Sort channel indices based on scores (ascending order)
      indices = list(np.argsort(scores))
      # Select top channels (highest scores → most important)
      high_score_indices = indices[::-1][: int(len(indices) * ratio_channels_to_ablate)]
      # Optionally also include lowest scoring channels (least important)
      low_score_indices = indices[: int(len(indices) * ratio_channels_to_ablate)]
      # Combine selected indices
      self.indices = np.int32(high_score_indices + low_score_indices)
      # Return indices of channels to be ablated
      return self.indices

    # Function to prepare the next batch of activations for ablation
    def set_next_batch(self,input_batch_index,activations,num_channels_to_ablate):
      """
      function prepares a batch of activations for ablation experiments.
      """
      # Select activations for a single input from the batch
      # Shape: (channels, height, width)
      selected = activations[input_batch_index, :, :, :]
      # Clone to avoid modifying original activations add batch dimension → (1, channels, height, width)
      # Repeat it num_channels_to_ablate times along batch dimension
      # Final shape: (num_channels_to_ablate, channels, height, width)
      self.activations = selected.clone().unsqueeze(0).repeat(num_channels_to_ablate, 1, 1, 1)

    # Function to perform the actual ablation on selected activation channels
    def __call__(self, x):
      # Start with the batch of activations prepared earlier
      output = self.activations
      # Loop through each sample in the batch
      for i in range(output.size(0)):
        # Check if the minimum activation is 0 many networks have ReLU, so min = 0 is common
        if torch.min(output) == 0:
            # Zero out the selected channel(s) for ablation self.indices[i] indicates which channel(s) to ablate
            output[i, self.indices[i], :] = 0
        else:
            # If activations can be negative, use a very negative value this deviates from the original paper but ensures ablation effect
            ABLATION_VALUE = 1e7
            output[i, self.indices[i], :] = torch.min(output) - ABLATION_VALUE
      # Return the batch of activations with selected channels ablated
      return output

class AblationCAM(BaseCAM):
  def __init__(self,model: torch.nn.Module,target_layers: List[torch.nn.Module],
               reshape_transform: Callable = None,ablation_layer: torch.nn.Module = AblationLayer(),
               batch_size: int = 32,ratio_channels_to_ablate: float = 1.0):
    # Initialize the parent BaseCAM class
    super(AblationCAM, self).__init__(model, target_layers, reshape_transform)
    # Batch size for ablation experiments activations may be repeated and processed in batches for efficiency
    self.batch_size = batch_size
    # Layer that performs the actual ablation contains methods for generating masks and zeroing out channels
    self.ablation_layer = ablation_layer
    # Fraction of channels to ablate in each experiment
    # 1.0 → all channels; smaller values → only top-ranked channels
    self.ratio_channels_to_ablate = ratio_channels_to_ablate

  # Helper method to save raw activations from the target layer
  def save_activation(self, module, input, output):
    """
    Store the output of a target layer for later use in ablation.
    """
    self.activations = output

  # Assemble scores for all channels after ablation experiments
  def assemble_ablation_scores(self,new_scores: list,original_score: float,ablated_channels: np.ndarray,number_of_channels: int):
    """
    Create a final array of channel importance scores:
    - For channels that were actually ablated, use the new scores from the experiment
    - For channels that were skipped, assign the original model score
    """
    # Pointer to iterate over ablated_channels
    index = 0
    # List to store final scores
    result = []
    # Sort the indices of ablated channels to maintain correct order
    sorted_indices = np.argsort(ablated_channels)
    ablated_channels = ablated_channels[sorted_indices]
    new_scores = np.float32(new_scores)[sorted_indices]
    # Loop over all channels
    for i in range(number_of_channels):
      if index < len(ablated_channels) and ablated_channels[index] == i:
        # If this channel was ablated, use its experimental score
        weight = new_scores[index]
        index += 1
      else:
        # If skipped, use the original score
        weight = original_score
      result.append(weight)
    # Return final channel-wise importance scores
    return result

  # Compute CAM weights using Ablation-CAM (gradient-free method)
  def get_cam_weights(self,input_tensor: torch.Tensor,target_layer: torch.nn.Module,
                      targets: List[Callable],activations: torch.Tensor,grads: torch.Tensor):
    # Cache original activations of the target layer
    handle = target_layer.register_forward_hook(self.save_activation)
    with torch.no_grad():
      # Forward pass
      outputs = self.model(input_tensor)
      # Remove hook after forward
      handle.remove()
      # Compute original target scores for each input in batch
      original_scores = np.float32([target(output).cpu().item() for target, output in zip(targets, outputs)])
    # Replace the target layer with the ablation layer this layer allows systematically zeroing out channels
    ablation_layer = self.ablation_layer
    replace_layer_recursive(self.model, target_layer, ablation_layer)
    # Total channels is target layer
    number_of_channels = activations.shape[1]
    # list to store channel importance scores
    weights = []
    # Perform gradient-free ablation experiments
    with torch.no_grad():
      # Loop over each input in the batch
      for batch_index, (target, tensor) in enumerate(zip(targets, input_tensor)):
        # Scores after ablating channels for this input
        new_scores = []
        # Repeat the input tensor to process multiple ablations in batch
        batch_tensor = tensor.repeat(self.batch_size, 1, 1, 1)
        # Decide which channels to ablate
        channels_to_ablate = ablation_layer.activations_to_be_ablated(activations[batch_index, :], self.ratio_channels_to_ablate)
        number_channels_to_ablate = len(channels_to_ablate)
        # Process ablations in mini-batches
        for i in tqdm.tqdm(range(0, number_channels_to_ablate, self.batch_size)):
          # Adjust batch size if near the end
          if i + self.batch_size > number_channels_to_ablate:
            batch_tensor = batch_tensor[:(number_channels_to_ablate - i)]
          # Prepare the next batch of activations with channels to ablate
          ablation_layer.set_next_batch(input_batch_index=batch_index,
                                        activations=self.activations,
                                        num_channels_to_ablate=batch_tensor.size(0)
                                        )
          # Forward pass with ablated activations, compute new target scores
          score = [target(o).cpu().item() for o in self.model(batch_tensor)]
          new_scores.extend(score)
          # Remove already processed indices from ablation_layer
          ablation_layer.indices = ablation_layer.indices[batch_tensor.size(0):]
        # Combine scores for ablated and skipped channels
        new_scores = self.assemble_ablation_scores(new_scores,original_scores[batch_index],
                                                   channels_to_ablate,number_of_channels)
        # Append this input's weights to the overall list
        weights.extend(new_scores)
      # Convert to NumPy array and reshape to (batch, channels)
      weights = np.float32(weights)
      weights = weights.reshape(activations.shape[:2])
      # Normalize weights: relative drop compared to original score
      original_scores = original_scores[:, None]  # Shape: (batch, 1)
      weights = (original_scores - weights) / original_scores
      # Restore the original model (replace ablation layer back)
      replace_layer_recursive(self.model, ablation_layer, target_layer)
      # Return final CAM weights for each channel
      return weights

# Helper class to define a target for a planning network it computes a loss between the predicted waypoints and a reference target
class PlannerTarget:
    def __init__(self, target_wp):
        self.target_wp = target_wp
        if torch.cuda.is_available():
            self.target_wp = self.target_wp.cuda()
    def __call__(self, model_output):
        """
        Compute the L1 loss between the model's predicted waypoints and the target waypoints.
        """
        _, debug_outputs = model_output
        # Convert predicted waypoints (numpy) to tensor, compute absolute differences
        l1_loss = torch.mean(torch.abs(torch.from_numpy(debug_outputs['pred_wp']) - self.target_wp))
        return l1_loss





