# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmNjSQ8CRPt9fKGkRIV35IcOVJOpo4W9
"""

!pip install --upgrade pip setuptools
!pip install mmcv-lite

import mmcv
print(mmcv.__version__)

import torch.nn as nn
def normal_init(module, mean=0, std=1, bias=0):
    """
    Initialize the weights and bias of a neural network module.
    """
    # Check if the module has a weight parameter and it's not None
    if hasattr(module, 'weight') and module.weight is not None:
        # Initialize weights using normal (Gaussian) distribution
        # weight ~ N(mean, std)
        nn.init.normal_(module.weight, mean, std)
    # Check if the module has a bias parameter and it's not None
    if hasattr(module, 'bias') and module.bias is not None:
        # Initialize bias with a constant value
        nn.init.constant_(module.bias, bias)

import math
def bias_init_with_prob(prior_prob):
    """
    Compute bias initialization value based on prior probability.
    """
    # Formula:
    # bias = -log((1 - p) / p)
    # this converts probability → logit space
    # (inverse of sigmoid function)
    return float(-math.log((1 - prior_prob) / prior_prob))

import torch
from torchvision.ops import nms
def batched_nms_pytorch(boxes, scores, labels, iou_threshold):
    """
    Perform class-wise Non-Maximum Suppression (NMS).
    """
    # store final selected indices
    keep_indices = []
    # Get unique class labels (e.g., car, person, bike)
    unique_labels = labels.unique()
    # Apply NMS separately for each class
    for cls in unique_labels:
        # Create mask for current class
        cls_mask = labels == cls
        # Select boxes and scores belonging to this class
        cls_boxes = boxes[cls_mask]
        cls_scores = scores[cls_mask]
        # Apply standard NMS (removes overlapping boxes)
        cls_keep = nms(cls_boxes, cls_scores, iou_threshold)
        # Get original indices of these class-specific boxes
        original_indices = torch.nonzero(cls_mask).squeeze(1)
        # Map NMS-selected indices back to original indexing
        keep_indices.append(original_indices[cls_keep])
    # Concatenate indices from all classes
    return torch.cat(keep_indices)

import torch
def force_fp32(func):
    """
    Decorator to ensure all tensor inputs to a function are converted to float32.
    Useful when working with mixed precision (FP16), but certain operations
    require higher numerical stability in FP32.
    """
    def wrapper(*args, **kwargs):
        # Convert all positional arguments to float32 if they are tensors
        new_args = [a.float() if isinstance(a, torch.Tensor) else a for a in args]
        # Convert all keyword arguments to float32 if they are tensors
        new_kwargs = {k: v.float() if isinstance(v, torch.Tensor) else v for k, v in kwargs.items()}
        # Call the original function with converted arguments
        return func(*new_args, **new_kwargs)
    # Return the wrapped function
    return wrapper

def multi_apply(func, *args, **kwargs):
    """
    Apply a function to multiple inputs (like map) and group outputs by their type.
    """
    # Create a new function that includes kwargs (if provided)
    # This ensures func can be called with both args and kwargs
    pfunc = lambda *a: func(*a, **kwargs) if kwargs else func(*a)
    # Apply function to each set of inputs (like map)
    map_results = map(pfunc, *args)
    # Convert map object to list
    results = list(map_results)
    # Transpose the list of tuples zip(*results) converts:
    return tuple(map(list, zip(*results)))

import torch.nn as nn
class DetectionHead(nn.Module):
    """
    Simple detection head.
    This head takes feature maps (e.g., from backbone/FPN) and produces output predictions (e.g., class scores).
    """
    def __init__(self):
        # Initialize parent class (nn.Module)
        super().__init__()
        # Convolution layer:
        # Input channels = 256 (feature map depth)
        # Output channels = 80 (e.g., number of classes like COCO dataset)
        # Kernel size = 3x3
        # padding=1 → keeps spatial size same (H, W unchanged)
        self.conv = nn.Conv2d(256, 80, 3, padding=1)
    def forward(self, x):
        """
        Forward pass of detection head.
        """
        # Apply convolution to generate predictions
        return self.conv(x)

import torch.nn as nn
class MultiTaskLoss(nn.Module):
    """
    Multi-task loss for detection models.
    Combines:
    - Classification loss (predicting class labels)
    - Regression loss (predicting bounding boxes)
    Total loss = classification loss + regression loss
    """
    def __init__(self):
        # Initialize parent class
        super().__init__()
        # Classification loss:
        # Used for predicting class labels (multi-class classification)
        # Input: logits (not softmax), Target: class indices
        self.cls_loss = nn.CrossEntropyLoss()
        # Regression loss:
        # Used for bounding box prediction (x, y, w, h or x1, y1, x2, y2)
        # SmoothL1 is robust to outliers compared to MSE
        self.reg_loss = nn.SmoothL1Loss()
    def forward(self, pred_cls, gt_cls, pred_box, gt_box):
        """
        Forward pass to compute total loss.
        Args:
            pred_cls: predicted class scores (logits) → shape (N, C)
            gt_cls: ground truth class labels → shape (N,)
            pred_box: predicted bounding boxes → shape (N, 4)
            gt_box: ground truth bounding boxes → shape (N, 4)
        """
        # Compute classification loss
        loss_cls = self.cls_loss(pred_cls, gt_cls)
        # Compute bounding box regression loss
        loss_box = self.reg_loss(pred_box, gt_box)
        # Total loss = sum of both tasks
        return loss_cls + loss_box

import torch
def gaussian_radius(det_size, min_overlap=0.7):
    """
    Compute the radius of a 2D Gaussian for object heatmap generation.
    Used in CenterNet-style detectors to determine how large the Gaussian
    should be for a given object size, ensuring a minimum IoU overlap.
    Args:
        det_size (tuple): (height, width) of the bounding box
        min_overlap (float): desired minimum IoU overlap (default = 0.7)
    """
    height, width = det_size
    # -------------------------------
    # Case 1: one corner inside
    # Solve quadratic equation: r^2 + (h + w)r + (1 - overlap)/(1 + overlap) * w*h = 0
    # -------------------------------
    a1 = 1
    b1 = height + width
    c1 = width * height * (1 - min_overlap) / (1 + min_overlap)
    # Compute discriminant and radius
    sq1 = torch.sqrt(torch.tensor(b1**2 - 4 * a1 * c1))
    r1 = (b1 + sq1) / 2
    # -------------------------------
    # Case 2: both corners inside
    # Solve: 4r^2 + 2(h + w)r + (1 - overlap) * w*h = 0
    # -------------------------------
    a2 = 4
    b2 = 2 * (height + width)
    c2 = (1 - min_overlap) * width * height
    sq2 = torch.sqrt(torch.tensor(b2**2 - 4 * a2 * c2))
    r2 = (b2 + sq2) / 2
    # -------------------------------
    # Case 3: center inside
    # Solve: 4*overlap*r^2 - 2*overlap*(h + w)r + (overlap - 1)*w*h = 0
    # -------------------------------
    a3 = 4 * min_overlap
    b3 = -2 * min_overlap * (height + width)
    c3 = (min_overlap - 1) * width * height
    sq3 = torch.sqrt(torch.tensor(b3**2 - 4 * a3 * c3))
    r3 = (b3 + sq3) / 2
    # Return the smallest radius that satisfies all conditions
    return min(r1, r2, r3)

import torch
import math
def gaussian2D(shape, sigma=1):
    """
    Generate a 2D Gaussian kernel.
    Args:
        shape (tuple): (height, width) of the Gaussian kernel
        sigma (float): standard deviation (controls spread of Gaussian)
    """
    # Compute center offsets (so Gaussian is centered at 0,0)
    m, n = [(ss - 1.) / 2. for ss in shape]
    # Create coordinate grid:
    # y: vertical axis, x: horizontal axis
    # meshgrid creates matrices of coordinates
    y, x = torch.meshgrid(
        torch.arange(-m, m + 1),
        torch.arange(-n, n + 1),
        indexing='ij'  # ensures matrix indexing (row, col)
    )
    # Apply 2D Gaussian formula: G(x,y) = exp(-(x^2 + y^2) / (2 * sigma^2))
    h = torch.exp(-(x * x + y * y) / (2 * sigma * sigma))
    # Remove very small values (numerical stability optimization)
    h[h < torch.finfo(h.dtype).eps * h.max()] = 0
    # Return Gaussian kernel
    return h

import torch
def draw_gaussian(heatmap, center, radius, k=1):
    """
    Draw a 2D Gaussian on a heatmap at a given center.
    Args:
        heatmap (Tensor): shape (H, W), existing heatmap
        center (tuple): (x, y) coordinates where Gaussian is placed
        radius (int): radius of Gaussian (controls size)
        k (float): scaling factor (peak value multiplier)
    """
    # Diameter of Gaussian kernel
    diameter = 2 * radius + 1
    # Generate Gaussian kernel
    # sigma = diameter / 6 → standard choice for smooth spread
    gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
    # Convert center coordinates to integers
    x, y = int(center[0]), int(center[1])
    # Get heatmap dimensions
    height, width = heatmap.shape
    # Compute how much Gaussian fits within heatmap boundaries
    # (handles edge cases when object is near border)
    left, right = min(x, radius), min(width - x, radius + 1)
    top, bottom = min(y, radius), min(height - y, radius + 1)
    # Extract region of heatmap where Gaussian will be applied
    masked_heatmap = heatmap[y - top:y + bottom, x - left:x + right]
    # Extract corresponding region from Gaussian kernel
    masked_gaussian = gaussian[radius - top:radius + bottom,radius - left:radius + right]
    # Ensure valid shapes (avoid empty slices)
    if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0:
        # Apply Gaussian using element-wise maximum
        torch.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)
    # Return updated heatmap
    return heatmap

import torch
import torch.nn.functional as F
def get_local_maximum(heatmap, kernel=3):
    """
    Extract local maxima (peaks) from a heatmap.

    Args:
        heatmap (Tensor): shape (B, C, H, W) or (H, W)
        kernel (int): size of neighborhood to consider (default = 3)

    Returns:
        Tensor: heatmap with only local maxima retained (others set to 0)
    """
    # Compute padding so output size remains same after max pooling
    pad = (kernel - 1) // 2
    # Apply max pooling: For each pixel, replace it with the maximum value in its local neighborhood
    hmax = F.max_pool2d(heatmap, kernel_size=kernel, stride=1, padding=pad)
    # Create a mask: Keep only positions where original value == local maximum
    keep = (hmax == heatmap).float()
    # Multiply mask with heatmap:
    # - Local maxima → kept
    # - Non-max values → set to 0
    return heatmap * keep

import torch
def get_topk_from_heatmap(heatmap, K=40):
    """
    Extract top-K keypoints (object centers) from a heatmap.

    Args:
        heatmap (Tensor): shape (B, C, H, W)
                          B = batch size
                          C = number of classes
                          H, W = spatial dimensions
        K (int): number of top detections to keep

    Returns:
        final_scores: (B, K) → top scores
        final_inds: (B, K) → flattened indices
        topk_clses: (B, K) → class IDs
        final_ys: (B, K) → y coordinates
        final_xs: (B, K) → x coordinates
    """
    B, C, H, W = heatmap.shape
    # ----------------------------------------
    # Step 1: Flatten spatial dimensions
    # (B, C, H, W) → (B, C, H*W)
    # ----------------------------------------
    heatmap = heatmap.view(B, C, -1)
    # ----------------------------------------
    # Step 2: Get top-K scores per class
    # ----------------------------------------
    topk_scores, topk_inds = torch.topk(heatmap, K)
    # ----------------------------------------
    # Step 3: Convert flattened indices → (x, y)
    # index = y * W + x
    # ----------------------------------------
    topk_inds = topk_inds % (H * W)
    topk_ys = (topk_inds // W).int()
    topk_xs = (topk_inds % W).int()
    # ----------------------------------------
    # Step 4: Flatten across all classes
    # (B, C, K) → (B, C*K)
    # ----------------------------------------
    topk_scores = topk_scores.view(B, -1)
    topk_inds = topk_inds.view(B, -1)
    topk_ys = topk_ys.view(B, -1)
    topk_xs = topk_xs.view(B, -1)
    # ----------------------------------------
    # Step 5: Select top-K across ALL classes
    # ----------------------------------------
    final_scores, topk_ind = torch.topk(topk_scores, K)
    # ----------------------------------------
    # Step 6: Gather corresponding indices
    # ----------------------------------------
    final_inds = topk_inds.gather(1, topk_ind)
    final_ys = topk_ys.gather(1, topk_ind)
    final_xs = topk_xs.gather(1, topk_ind)
    # ----------------------------------------
    # Step 7: Get class labels
    # Each class contributed K entries → divide index by K
    # ----------------------------------------
    topk_clses = (topk_ind // K).int()
    # Return final detections
    return final_scores, final_inds, topk_clses, final_ys, final_xs

import torch
def transpose_and_gather_feat(feat, ind):
    """
    Extract features at specific spatial locations (indices).

    Args:
        feat (Tensor): shape (B, C, H, W)
                       feature map from network
        ind (Tensor): shape (B, K)
                      flattened indices of positions (e.g., object centers)

    Returns:
        Tensor: gathered features of shape (B, K, C)
    """
    # ----------------------------------------
    # Step 1: Rearrange dimensions
    # (B, C, H, W) → (B, H, W, C)
    # This makes spatial dimensions come before channels
    # ----------------------------------------
    feat = feat.permute(0, 2, 3, 1).contiguous()
    # ----------------------------------------
    # Step 2: Flatten spatial dimensions
    # (B, H, W, C) → (B, H*W, C)
    # Each spatial location becomes a row
    # ----------------------------------------
    feat = feat.view(feat.size(0), -1, feat.size(3))
    # ----------------------------------------
    # Step 3: Prepare indices for gathering
    # ind: (B, K) → (B, K, C)
    # Expand indices to match feature dimension
    # ----------------------------------------
    ind = ind.unsqueeze(2).expand(ind.size(0), ind.size(1), feat.size(2))
    # ----------------------------------------
    # Step 4: Gather features at specified indices
    # Select K positions from H*W locations
    # ----------------------------------------
    feat = feat.gather(1, ind)
    # Output shape: (B, K, C)
    return feat

import torch
import torch.nn as nn
class BaseDenseHead(nn.Module):
    """
    Base class for dense prediction heads in detection models.
    This is an abstract class that defines the common interface for:
    - forward pass (feature → predictions)
    - loss computation (training)
    - prediction/inference (post-processing)
    It is similar to MMDetection's BaseDenseHead but simplified for pure PyTorch.
    """
    def __init__(self):
        # Initialize nn.Module (required for all PyTorch models)
        super().__init__()
    def forward(self, feats):
        """
        Forward pass: generate predictions from feature maps.
        Args:
            feats (list of Tensor):
                Feature maps from backbone/FPN
                Example: [(B, C, H1, W1), (B, C, H2, W2), ...]
        Returns:
            preds: model outputs (e.g., class scores, bbox predictions)
        NOTE:
            Must be implemented in child class.
        """
        raise NotImplementedError
    def loss(self, preds, targets):
        """
        Compute training loss.
        Args:
            preds: predictions from forward()
            targets: ground truth annotations (labels, boxes, etc.)
        Returns:
            dict or Tensor: loss values
        NOTE:
            Must be implemented in child class.
        """
        raise NotImplementedError
    def predict(self, preds):
        """
        Inference / post-processing step.
        Converts raw model outputs into final detections:
        - apply sigmoid/softmax
        - decode bounding boxes
        - apply NMS
        Args:
            preds: raw outputs from forward()
        Returns:
            final detections (boxes, scores, labels)
        """
        raise NotImplementedError

import torch
import torch.nn as nn
class MyDenseHead(BaseDenseHead):
    """
    A simple dense detection head.
    Performs:
    - Feature processing
    - Classification (what object)
    - Regression (where object is)
    Supports multi-scale features (e.g., from FPN).
    """
    def __init__(self, in_channels, num_classes):
        # Initialize base class
        super().__init__()
        # Shared convolution layer: Reduces/learns features from backbone output
        self.conv = nn.Conv2d(in_channels, 64, 3, padding=1)
        # Classification layer: Outputs class scores for each spatial location
        self.cls_layer = nn.Conv2d(64, num_classes, 1)
        # Regression layer:Outputs bounding box values (x, y, w, h or x1, y1, x2, y2)
        self.reg_layer = nn.Conv2d(64, 4, 1)
        # Classification loss: Compares predicted class logits with ground truth labels
        self.cls_loss = nn.CrossEntropyLoss()
        # Regression loss: Measures difference between predicted and GT boxes
        self.reg_loss = nn.SmoothL1Loss()
    def forward(self, feats):
        """
        Forward pass over multi-scale feature maps.
        """
        outputs = []
        # Process each feature map independently
        for x in feats:
            # Shared feature extraction
            x = self.conv(x)
            # Predict class scores
            cls = self.cls_layer(x)
            # Predict bounding boxes
            reg = self.reg_layer(x)
            # Store predictions for this level
            outputs.append((cls, reg))
        return outputs
    def loss(self, preds, targets):
        """
        Compute total loss across all feature levels.
        """
        # accumulate classification loss
        loss_cls = 0
        # accumulate regression loss
        loss_reg = 0
        # Loop over each feature level
        for (cls, reg), (gt_cls, gt_reg) in zip(preds, targets):
            # Compute classification loss
            loss_cls += self.cls_loss(cls, gt_cls)
            # Compute bounding box regression loss
            loss_reg += self.reg_loss(reg, gt_reg)
        # Return both losses separately (useful for monitoring)
        return {"loss_cls": loss_cls,"loss_reg": loss_reg}
    def predict(self, preds):
        """
        Inference step: convert raw outputs into usable predictions.
        """
        results = []
        for cls, reg in preds:
            # convert logits → probabilities softmax across class dimension
            scores = torch.softmax(cls, dim=1)
            # append results for this feature level post-processing like NMS not yet applied
            results.append((scores, reg))
        return results

import torch
from torchvision.ops import nms
def simple_test_bboxes(cls_scores, bbox_preds, score_thr=0.05, iou_thr=0.5):
    """
    Perform simple inference for object detection:
    - Select best class per box
    - Filter low-confidence predictions
    - Apply Non-Maximum Suppression (NMS)
    Args:
        cls_scores (Tensor): shape (N, C)
            → class scores (logits or probabilities)
        bbox_preds (Tensor): shape (N, 4)
            → predicted bounding boxes (x1, y1, x2, y2)
        score_thr (float): threshold to filter low-confidence detections
        iou_thr (float): IoU threshold for NMS
    """
    # Select best class for each box
    # - scores → highest class score per box
    # - labels → corresponding class index
    scores, labels = torch.max(cls_scores, dim=1)
    # Filter low-confidence detections
    keep = scores > score_thr
    scores = scores[keep]
    labels = labels[keep]
    boxes = bbox_preds[keep]
    # Apply Non-Maximum Suppression (NMS) removes overlapping boxes with lower scores
    keep = nms(boxes, scores, iou_thr)
    # Return final filtered detections
    return boxes[keep], scores[keep], labels[keep]

import torch
def inference_from_features(feats, model):
    """
    Perform inference from multi-scale feature maps.
    Args:
        feats: list of feature maps [(B, C, H, W), ...]
               typically from backbone/FPN
        model: detection head with method `forward_single`
    Returns:
        Tuple:
            - all_boxes: concatenated bounding boxes
            - all_scores: corresponding confidence scores
            - all_labels: predicted class labels
    """
    # Lists to store results from all feature levels
    all_boxes = []
    all_scores = []
    all_labels = []
    # ----------------------------------------
    # Loop over each feature map (multi-scale)
    # ----------------------------------------
    for feat in feats:
        # Get predictions for a single feature map
        # cls: (B, C, H, W) → class scores
        # reg: (B, 4, H, W) → bounding boxes
        cls, reg = model.forward_single(feat)
        # Extract dimensions
        B, C, H, W = cls.shape
        # Reshape classification output
        # (B, C, H, W) → (B, H, W, C) → (B*H*W, C)
        # Each spatial location becomes a detection
        cls = cls.permute(0, 2, 3, 1).reshape(-1, C)
        # Reshape regression output
        # (B, 4, H, W) → (B, H, W, 4) → (B*H*W, 4)
        reg = reg.permute(0, 2, 3, 1).reshape(-1, 4)
        # Apply post-processing (threshold + NMS)
        boxes, scores, labels = simple_test_bboxes(cls, reg)
        # Store results from this feature level
        all_boxes.append(boxes)
        all_scores.append(scores)
        all_labels.append(labels)
    # Combine results from all feature levels
    return (
        torch.cat(all_boxes),   # all detected boxes
        torch.cat(all_scores),  # all scores
        torch.cat(all_labels),  # all class labels
    )

import torch
from torchvision.ops import nms
def simple_test_bboxes(cls_scores, bbox_preds, score_thr=0.05, iou_thr=0.5):
    """
    Perform basic object detection inference.
    Args:
        cls_scores (Tensor): shape (N, C)
            → class scores (logits or probabilities)
        bbox_preds (Tensor): shape (N, 4)
            → predicted bounding boxes (x1, y1, x2, y2)
        score_thr (float): confidence threshold
        iou_thr (float): IoU threshold for NMS
    Returns:
        boxes (Tensor): filtered bounding boxes
        scores (Tensor): confidence scores
        labels (Tensor): predicted class IDs
    """
    # Step 1: Select highest scoring class per box
    # - scores: max score for each box
    # - labels: index of class with highest score
    scores, labels = torch.max(cls_scores, dim=1)
    # Step 2: Remove low-confidence detections
    keep = scores > score_thr
    # Filter boxes, scores, and labels
    scores = scores[keep]
    labels = labels[keep]
    boxes = bbox_preds[keep]
    # Step 3: Apply Non-Maximum Suppression (NMS)
    # Removes overlapping boxes with lower scores
    keep = nms(boxes, scores, iou_thr)
    # Return final detections
    return boxes[keep], scores[keep], labels[keep]

def inference_from_feature_map(cls, reg, score_thr=0.05, iou_thr=0.5):
    """
    Perform inference from a single feature map.
    Args:
        cls (Tensor): shape (B, C, H, W)
            → class scores for each spatial location
        reg (Tensor): shape (B, 4, H, W)
            → bounding box predictions for each location
        score_thr (float): confidence threshold
        iou_thr (float): IoU threshold for NMS
    Returns:
        boxes, scores, labels → final detections
    """
    # Extract dimensions
    B, C, H, W = cls.shape
    # Step 1: Reshape classification output (B, C, H, W) → (B, H, W, C) → (B*H*W, C) Each pixel becomes a detection candidate
    cls = cls.permute(0, 2, 3, 1).reshape(-1, C)
    # Step 2: Reshape regression output (B, 4, H, W) → (B, H, W, 4) → (B*H*W, 4)
    reg = reg.permute(0, 2, 3, 1).reshape(-1, 4)
    # Step 3: Apply post-processing
    # - select best class
    # - filter low scores
    # - apply NMS
    return simple_test_bboxes(cls, reg, score_thr, iou_thr)

import torch
def inference_multi_level(feats, model):
    """
    Perform inference using multi-scale feature maps (e.g., FPN).
    Args:
        feats: list of feature maps [(B, C, H1, W1), (B, C, H2, W2), ...]
        model: detection head with method `forward_single`
    Returns:
        Tuple:
            - all_boxes: concatenated bounding boxes from all levels
            - all_scores: corresponding confidence scores
            - all_labels: predicted class labels
    """
    # Initialize lists to collect results from all feature levels
    all_boxes, all_scores, all_labels = [], [], []
    # Loop through each feature map (multi-scale)
    for feat in feats:
        # Get predictions from a single feature level
        # cls: (B, C, H, W) → class scores
        # reg: (B, 4, H, W) → bounding boxes
        cls, reg = model.forward_single(feat)
        # Convert feature map → detections
        # (flatten + threshold + NMS)
        boxes, scores, labels = inference_from_feature_map(cls, reg)
        # Store results for this level
        all_boxes.append(boxes)
        all_scores.append(scores)
        all_labels.append(labels)
    # Merge detections from all feature levels
    return (
        torch.cat(all_boxes),   # all bounding boxes
        torch.cat(all_scores),  # all confidence scores
        torch.cat(all_labels),  # all class labels
    )

import torch
import torch.nn as nn
# Placeholder for BBoxTestMixin
class BBoxTestMixin:
    pass
# Placeholder for build_loss function
def build_loss(cfg):
    # This is a placeholder. In a real implementation, it would create
    # and return a loss function based on the provided configuration.
    # For now, it returns a dummy nn.Module if a type is specified.
    # Gaussian Focal Loss (approximation)
    if cfg and 'type' in cfg and cfg['type'] == 'GaussianFocalLoss':
        return nn.MSELoss()
    # L1 Loss (absolute error)
    elif cfg and 'type' in cfg and cfg['type'] == 'L1Loss':
        return nn.L1Loss()
    # Cross Entropy Loss (classification)
    elif cfg and 'type' in cfg and cfg['type'] == 'CrossEntropyLoss':
        return nn.CrossEntropyLoss()
    # Smooth L1 Loss (robust regression)
    elif cfg and 'type' in cfg and cfg['type'] == 'SmoothL1Loss':
        return nn.SmoothL1Loss()
    # Default case: unknown config
    else:
        return nn.Module()
# Placeholder for _build_head method within LidarCenterNetHead
# This will be defined as a static method or a regular method that returns a dummy head.
# -----------------------------------------------------------------------------
# LidarCenterNetHead
# -----------------------------------------------------------------------------
# This class defines a custom detection head based on the CenterNet approach
# (Objects as Points). It is designed for LiDAR-based object detection tasks.
#
# Instead of predicting bounding boxes directly, CenterNet represents objects
# as keypoints (center points) on a heatmap and regresses additional properties.
#
# In this implementation, the head predicts:
#   1. Heatmap           → Object center probability per class
#   2. Width & Height    → Bounding box size (2D)
#   3. Offset            → Sub-pixel refinement of center location
#   4. Yaw Class         → Discrete orientation bins
#   5. Yaw Residual      → Continuous correction for orientation
#   6. Velocity          → Object speed estimation
#   7. Brake             → Binary classification (e.g., braking state)
#
# -----------------------------------------------------------------------------
class LidarCenterNetHead(BaseDenseHead, BBoxTestMixin):
    def __init__(self,
                 in_channel,        # Number of input feature channels
                 feat_channel,      # Number of hidden/intermediate channels
                 num_classes,       # Number of object classes (excluding background)
                 # Loss functions for each prediction branch
                 loss_center_heatmap=dict(type='GaussianFocalLoss', loss_weight=1.0),
                 loss_wh=dict(type='L1Loss', loss_weight=0.1),
                 loss_offset=dict(type='L1Loss', loss_weight=1.0),
                 loss_dir_class=dict(type='CrossEntropyLoss', loss_weight=1.0),
                 loss_dir_res=dict(type='SmoothL1Loss', loss_weight=1.0),
                 loss_velocity=dict(type='L1Loss', loss_weight=1.0),
                 loss_brake=dict(type='CrossEntropyLoss', loss_weight=1.0),
                 train_cfg=None,    # Training configuration (e.g., direction bins)
                 test_cfg=None,     # Testing configuration
                 init_cfg=None):    # Weight initialization config
        # Initialize parent class
        super(LidarCenterNetHead, self).__init__(init_cfg)
        # Store number of classes
        self.num_classes = num_classes
        # Define a placeholder for _build_head
        def _build_head_placeholder(in_c, feat_c, out_c):
            return nn.Sequential(nn.Conv2d(in_c, feat_c, 3, padding=1),
                                 nn.ReLU(),nn.Conv2d(feat_c, out_c, 1)
                                 )
        self._build_head = _build_head_placeholder
        # ---------------------------------------------------------------------
        # Prediction Heads
        # Each head is a small neural network predicting a specific attribute
        # ---------------------------------------------------------------------
        # Heatmap head: predicts center point probability per class
        self.heatmap_head = self._build_head(in_channel, feat_channel, num_classes)
        # Width & Height head: predicts object size (w, h)
        self.wh_head = self._build_head(in_channel, feat_channel, 2)
        # Offset head: refines center position (x_offset, y_offset)
        self.offset_head = self._build_head(in_channel, feat_channel, 2)
        # Number of bins for discretizing orientation (yaw angle)
        # Ensure train_cfg is not None before accessing its attributes
        if train_cfg is None:
            # Provide a default value or raise an error if train_cfg is expected
            self.num_dir_bins = 2 # Default to 2 for a minimal example
        else:
            self.num_dir_bins = train_cfg.num_dir_bins
        # Yaw classification head: predicts orientation bin
        self.yaw_class_head = self._build_head(in_channel, feat_channel, self.num_dir_bins)
        # Yaw residual head: predicts fine-grained angle offset
        self.yaw_res_head = self._build_head(in_channel, feat_channel, 1)
        # Velocity head: predicts object speed
        self.velocity_head = self._build_head(in_channel, feat_channel, 1)
        # Brake head: predicts braking state (binary classification)
        self.brake_head = self._build_head(in_channel, feat_channel, 2)
        # ---------------------------------------------------------------------
        # Loss Functions: Each prediction head has a corresponding loss function
        # ---------------------------------------------------------------------
        self.loss_center_heatmap = build_loss(loss_center_heatmap)
        self.loss_wh = build_loss(loss_wh)
        self.loss_offset = build_loss(loss_offset)
        self.loss_dir_class = build_loss(loss_dir_class)
        self.loss_dir_res = build_loss(loss_dir_res)
        self.loss_velocity = build_loss(loss_velocity)
        self.loss_brake = build_loss(loss_brake)
        # Store training and testing configurations
        self.train_cfg = train_cfg
        self.test_cfg = test_cfg
        # Enable mixed precision training (FP16) if configured
        # Ensure train_cfg is not None before accessing its attributes
        self.fp16_enabled = train_cfg.fp16_enabled if train_cfg else False
        # Debug / iteration counter (can be used for logging)
        self.i = 0

# -------------------------------------------------------------------------
# Helper function to build a prediction head (branch)
# -------------------------------------------------------------------------
def _build_head(self, in_channel, feat_channel, out_channel):
    """
    Build a small convolutional head for a specific prediction task.
    Each head consists of:
    1. Conv layer (3x3) → extracts spatial features
    2. ReLU activation → introduces non-linearity
    3. Conv layer (1x1) → maps features to desired output channels
    Args:
        in_channel (int): Number of input feature channels.
        feat_channel (int): Number of intermediate feature channels.
        out_channel (int): Number of output channels (depends on task).
    Returns:
        nn.Sequential: A small CNN block used as a prediction head.
    """
    layer = nn.Sequential(
        # 3x3 convolution to process spatial features
        nn.Conv2d(in_channel, feat_channel, kernel_size=3, padding=1),
        # Activation function (inplace saves memory)
        nn.ReLU(inplace=True),
        # 1x1 convolution to produce final outputs
        nn.Conv2d(feat_channel, out_channel, kernel_size=1)
    )
    return layer
# -------------------------------------------------------------------------
# Initialize weights for all heads
# -------------------------------------------------------------------------
def init_weights(self):
    """
    Initialize model weights for better training stability.

    Special handling:
    - Heatmap head bias is initialized using a probability-based prior
      (helps stabilize early training in CenterNet).
    - Other heads use normal (Gaussian) initialization.
    """
    # ---------------------------------------------------------------------
    # Initialize heatmap head bias
    # ---------------------------------------------------------------------
    # This sets an initial low probability for object centers
    # (important for focal loss stability in early training)
    bias_init = bias_init_with_prob(
        self.train_cfg.center_net_bias_init_with_prob
    )
    # Apply bias initialization to last layer of heatmap head
    self.heatmap_head[-1].bias.data.fill_(bias_init)
    # ---------------------------------------------------------------------
    # Initialize weights for width/height and offset heads
    # ---------------------------------------------------------------------
    for head in [self.wh_head, self.offset_head]:
        for m in head.modules():
            # Apply only to convolution layers
            if isinstance(m, nn.Conv2d):
                # Initialize weights with normal distribution
                normal_init(m,std=self.train_cfg.center_net_normal_init_std)

# -------------------------------------------------------------------------
# Forward pass for multiple feature levels
# -------------------------------------------------------------------------
def forward(self, feats):
    """
    Forward pass for all feature maps.
    Note:
        CenterNet typically does NOT use FPN (Feature Pyramid Network),but this implementation still supports multiple feature levels.
    Args:
        feats (tuple[Tensor]):
            Tuple of feature maps from the backbone/neck.
            Each tensor has shape (B, C, H, W).
    Returns:
        Tuple of lists:
            - center_heatmap_preds: List of heatmaps (per level)
            - wh_preds: List of width/height predictions
            - offset_preds: List of offset predictions
            - yaw_class_preds: List of yaw class predictions
            - yaw_res_preds: List of yaw residual predictions
            - velocity_preds: List of velocity predictions
            - brake_preds: List of brake predictions
    """
    # Apply forward_single to each feature map level
    # multi_apply maps the function over all feature levels
    return multi_apply(self.forward_single, feats)
# -------------------------------------------------------------------------
# Forward pass for a single feature level
# -------------------------------------------------------------------------
def forward_single(self, feat):
    """
    Forward computation for a single feature map.

    Args:
        feat (Tensor):
            Feature map of shape (B, C, H, W)

    Returns:
        Tuple of predictions:
            - center_heatmap_pred: (B, num_classes, H, W)
            - wh_pred: (B, 2, H, W)
            - offset_pred: (B, 2, H, W)
            - yaw_class_pred: (B, num_dir_bins, H, W)
            - yaw_res_pred: (B, 1, H, W)
            - velocity_pred: (B, 1, H, W)
            - brake_pred: (B, 2, H, W)
    """
    # Heatmap prediction (object center probability)
    # Sigmoid converts logits → probabilities in range [0, 1]
    center_heatmap_pred = self.heatmap_head(feat).sigmoid()
    # Bounding box size prediction (width, height)
    wh_pred = self.wh_head(feat)
    # Center offset prediction (sub-pixel refinement)
    offset_pred = self.offset_head(feat)
    # ---------------------------------------------------------------------
    # Yaw (orientation) prediction
    # ---------------------------------------------------------------------
    # Discrete orientation class (which direction bin)
    yaw_class_pred = self.yaw_class_head(feat)
    # Continuous residual to refine orientation
    yaw_res_pred = self.yaw_res_head(feat)
    # ---------------------------------------------------------------------
    # Additional attributes
    # ---------------------------------------------------------------------
    # Velocity prediction (object speed)
    velocity_pred = self.velocity_head(feat)
    # Brake prediction (binary classification: brake / no brake)
    brake_pred = self.brake_head(feat)
    # ---------------------------------------------------------------------
    # Return all predictions for this feature level
    # ---------------------------------------------------------------------
    return (center_heatmap_pred,wh_pred,offset_pred,yaw_class_pred,
            yaw_res_pred,velocity_pred,brake_pred)

# -------------------------------------------------------------------------
# Loss computation for LidarCenterNetHead
# -------------------------------------------------------------------------
def loss(self,center_heatmap_preds,wh_preds,offset_preds,yaw_class_preds,yaw_res_preds,
         velocity_preds,brake_preds,gt_bboxes,gt_labels,img_metas,gt_bboxes_ignore=None):
    """
    Compute all training losses for the detection head.
    This function compares model predictions with ground truth targets and calculates losses for each prediction branch.
    Args:
        center_heatmap_preds (list[Tensor]):
            Predicted heatmaps (B, num_classes, H, W)
        wh_preds (list[Tensor]):
            Predicted width & height (B, 2, H, W)
        offset_preds (list[Tensor]):
            Predicted center offsets (B, 2, H, W)
        yaw_class_preds (list[Tensor]):
            Predicted orientation class logits
        yaw_res_preds (list[Tensor]):
            Predicted orientation residuals
        velocity_preds (list[Tensor]):
            Predicted object velocity
        brake_preds (list[Tensor]):
            Predicted brake state (binary classification)
        gt_bboxes (list[Tensor]):
            Ground truth bounding boxes (tl_x, tl_y, br_x, br_y)
        gt_labels (list[Tensor]):
            Class labels for each ground truth box
        img_metas (list[dict]):
            Metadata (image size, scale, etc.)
        gt_bboxes_ignore:
            Boxes to ignore during training
    Returns:
        dict[str, Tensor]:
            Dictionary of all computed losses
    """
    # ---------------------------------------------------------------------
    # implementation assumes single feature level (no FPN)
    # ---------------------------------------------------------------------
    assert len(center_heatmap_preds) == len(wh_preds) == len(offset_preds) == 1
    # Extract predictions for the only level
    center_heatmap_pred = center_heatmap_preds[0]
    wh_pred = wh_preds[0]
    offset_pred = offset_preds[0]
    yaw_class_pred = yaw_class_preds[0]
    yaw_res_pred = yaw_res_preds[0]
    velocity_pred = velocity_preds[0]
    brake_pred = brake_preds[0]
    # ---------------------------------------------------------------------
    # Generate training targets from ground truth
    # ---------------------------------------------------------------------
    target_result, avg_factor = self.get_targets(gt_bboxes,gt_labels,gt_bboxes_ignore,center_heatmap_pred.shape)
    # Extract individual targets
    center_heatmap_target = target_result['center_heatmap_target']
    wh_target = target_result['wh_target']
    yaw_class_target = target_result['yaw_class_target']
    yaw_res_target = target_result['yaw_res_target']
    offset_target = target_result['offset_target']
    velocity_target = target_result['velocity_target']
    brake_target = target_result['brake_target']
    # Weight mask (indicates valid object locations)
    wh_offset_target_weight = target_result['wh_offset_target_weight']
    # ---------------------------------------------------------------------
    # Compute losses for each prediction branch
    # ---------------------------------------------------------------------
    # Heatmap loss (object center classification)
    loss_center_heatmap = self.loss_center_heatmap(center_heatmap_pred,center_heatmap_target,avg_factor=avg_factor)
    # Width & Height regression loss
    # Multiplied avg_factor by 2 because it has 2 channels (w, h)
    loss_wh = self.loss_wh(wh_pred,wh_target,wh_offset_target_weight,avg_factor=avg_factor * 2)
    # Offset regression loss
    loss_offset = self.loss_offset(offset_pred,offset_target,wh_offset_target_weight,avg_factor=avg_factor * 2)
    # Yaw (orientation) classification loss
    loss_yaw_class = self.loss_dir_class(yaw_class_pred,yaw_class_target,wh_offset_target_weight[:, :1, ...],avg_factor=avg_factor)
    # Yaw residual regression loss
    loss_yaw_res = self.loss_dir_res(yaw_res_pred,yaw_res_target,wh_offset_target_weight[:, :1, ...],avg_factor=avg_factor)
    # Velocity regression loss
    loss_velocity = self.loss_velocity(velocity_pred,velocity_target,wh_offset_target_weight[:, :1, ...],avg_factor=avg_factor)
    # Brake classification loss
    loss_brake = self.loss_brake(brake_pred,brake_target,wh_offset_target_weight[:, :1, ...],avg_factor=avg_factor)
    # ---------------------------------------------------------------------
    # Return all losses as a dictionary
    # ---------------------------------------------------------------------
    return dict(loss_center_heatmap=loss_center_heatmap,loss_wh=loss_wh,
                loss_offset=loss_offset,loss_yaw_class=loss_yaw_class,
                loss_yaw_res=loss_yaw_res,loss_velocity=loss_velocity,
                loss_brake=loss_brake)

# -------------------------------------------------------------------------
# Convert continuous angle → discrete class + residual
# -------------------------------------------------------------------------
def angle2class(self, angle):
    """
    Convert a continuous angle into:
    1. A discrete class (bin index)
    2. A small residual (offset from bin center)
    this is commonly used for orientation (yaw) prediction in detection tasks.
    Instead of directly regressing angle (hard problem), we:
    - Classify angle into bins (coarse prediction)
    - Regress small offset within that bin (fine prediction)
    Args:
        angle (Tensor):Angle values in radians (range: 0 to 2π or -π to π)
    Returns:
        tuple:
            angle_cls (Tensor): Discrete class index (bin number)
            angle_res (Tensor): Residual offset from bin center
    """
    # ---------------------------------------------------------------------
    # Normalize angle to range [0, 2π)
    # ---------------------------------------------------------------------
    angle = angle % (2 * np.pi)
    # ---------------------------------------------------------------------
    # Compute size of each bin
    # Example: if num_dir_bins = 4 → each bin = 90° (π/2)
    # ---------------------------------------------------------------------
    angle_per_class = 2 * np.pi / float(self.num_dir_bins)
    # ---------------------------------------------------------------------
    # Shift angle by half bin size
    # This aligns bins so that class centers are evenly spaced
    # ---------------------------------------------------------------------
    shifted_angle = (angle + angle_per_class / 2) % (2 * np.pi)
    # ---------------------------------------------------------------------
    # Compute discrete class (bin index)
    #
    # NOTE:
    # - Using trunc (towards zero) instead of floor
    # - Works same as floor because angle is always positive
    # - Keeps backward compatibility with older models
    # ---------------------------------------------------------------------
    angle_cls = torch.div(shifted_angle,angle_per_class,rounding_mode="trunc")
    # ---------------------------------------------------------------------
    # Compute residual (fine offset from bin center)
    # Formula: residual = actual angle - center of assigned bin
    # ---------------------------------------------------------------------
    angle_res = shifted_angle - (angle_cls * angle_per_class + angle_per_class / 2)
    # Return:
    # - class index (integer)
    # - residual (float)
    return angle_cls.long(), angle_res

# -------------------------------------------------------------------------
# Convert discrete class + residual → continuous angle
# -------------------------------------------------------------------------
def class2angle(self, angle_cls, angle_res, limit_period=True):
    """
    Decode angle from:
    - Discrete class (bin index)
    - Residual (offset within bin)

    This is the inverse operation of `angle2class`.

    Args:
        angle_cls (Tensor):
            Predicted angle class (bin index)
        angle_res (Tensor):
            Predicted residual (fine offset)
        limit_period (bool):
            If True, constrain output angle to [-π, π]

    Returns:
        Tensor:
            Decoded continuous angle in radians
    """
    # ---------------------------------------------------------------------
    # Compute size of each bin
    # ---------------------------------------------------------------------
    angle_per_class = 2 * np.pi / float(self.num_dir_bins)
    # ---------------------------------------------------------------------
    # Compute center angle of the predicted bin
    # ---------------------------------------------------------------------
    angle_center = angle_cls.float() * angle_per_class
    # ---------------------------------------------------------------------
    # Add residual to get final continuous angle
    # final_angle = bin_center + small_offset
    # ---------------------------------------------------------------------
    angle = angle_center + angle_res
    # ---------------------------------------------------------------------
    # Optionally normalize angle to range [-π, π]
    # This avoids discontinuity issues (e.g., 359° ≈ -1°)
    # ---------------------------------------------------------------------
    if limit_period:
        angle[angle > np.pi] -= 2 * np.pi
    # Return decoded angle
    return angle

# -------------------------------------------------------------------------
# Generate training targets from ground truth annotations
# -------------------------------------------------------------------------
def get_targets(self, gt_bboxes, gt_labels, gt_ignores, feat_shape):
    """
    Convert ground truth annotations into training targets for all heads.
    This function maps GT boxes from image space → feature map space
    and creates targets for:
        - Heatmap (object centers)
        - Width & Height
        - Offset
        - Yaw (class + residual)
        - Velocity
        - Brake
        - Weight mask
    Args:
        gt_bboxes (list[Tensor]):
            Ground truth boxes per image
            Format: (x_center, y_center, w, h, yaw, velocity, brake)
        gt_labels (list[Tensor]):
            Class labels per object
        gt_ignores (list[Tensor]):
            Boolean mask to ignore certain objects
        feat_shape (list[int]):
            Shape of feature map → [B, C, H, W]
    Returns:
        target_result (dict):
            Dictionary containing all training targets
        avg_factor (float):
            Normalization factor (number of positive samples)
    """
    # ---------------------------------------------------------------------
    # Get original LiDAR resolution and feature map size
    # ---------------------------------------------------------------------
    img_h = self.train_cfg.lidar_resolution_height
    img_w = self.train_cfg.lidar_resolution_width
    bs, _, feat_h, feat_w = feat_shape
    # Compute scaling ratios (image → feature map)
    width_ratio = float(feat_w / img_w)
    height_ratio = float(feat_h / img_h)
    # ---------------------------------------------------------------------
    # Initialize all target tensors with zeros
    # ---------------------------------------------------------------------
    center_heatmap_target = gt_bboxes[-1].new_zeros([bs, self.num_classes, feat_h, feat_w])
    wh_target = gt_bboxes[-1].new_zeros([bs, 2, feat_h, feat_w])
    offset_target = gt_bboxes[-1].new_zeros([bs, 2, feat_h, feat_w])
    yaw_class_target = gt_bboxes[-1].new_zeros([bs, 1, feat_h, feat_w]).long()
    yaw_res_target = gt_bboxes[-1].new_zeros([bs, 1, feat_h, feat_w])
    velocity_target = gt_bboxes[-1].new_zeros([bs, 1, feat_h, feat_w])
    brake_target = gt_bboxes[-1].new_zeros([bs, 1, feat_h, feat_w]).long()
    # Weight mask → indicates valid object locations
    wh_offset_target_weight = gt_bboxes[-1].new_zeros([bs, 2, feat_h, feat_w])
    # ---------------------------------------------------------------------
    # Process each image in batch
    # ---------------------------------------------------------------------
    for batch_id in range(bs):
        gt_bbox = gt_bboxes[0][batch_id]
        gt_label = gt_labels[0][batch_id]
        gt_ignore = gt_ignores[0][batch_id]
        # -----------------------------------------------------------------
        # Convert center coordinates to feature map scale
        # -----------------------------------------------------------------
        center_x = gt_bbox[:, [0]] * width_ratio
        center_y = gt_bbox[:, [1]] * width_ratio
        gt_centers = torch.cat((center_x, center_y), dim=1)
        # -----------------------------------------------------------------
        # Loop over each object
        # -----------------------------------------------------------------
        for j, ct in enumerate(gt_centers):
            # Skip ignored objects
            if gt_ignore[j]:
                continue
            # Integer location (grid cell)
            ctx_int, cty_int = ct.int()
            # Floating-point center
            ctx, cty = ct
            # Scale box size to feature map
            scale_box_h = gt_bbox[j, 3] * height_ratio
            scale_box_w = gt_bbox[j, 2] * width_ratio
            # -----------------------------------------------------------------
            # Generate Gaussian heatmap for object center
            # -----------------------------------------------------------------
            radius = gaussian_radius([scale_box_h, scale_box_w],min_overlap=0.1)
            radius = max(2, int(radius))
            # Class index
            ind = gt_label[j].long()
            # Draw Gaussian peak on heatmap
            gen_gaussian_target(center_heatmap_target[batch_id, ind],[ctx_int, cty_int],radius)
            # -----------------------------------------------------------------
            # Width & Height targets
            # -----------------------------------------------------------------
            wh_target[batch_id, 0, cty_int, ctx_int] = scale_box_w
            wh_target[batch_id, 1, cty_int, ctx_int] = scale_box_h
            # -----------------------------------------------------------------
            # Yaw (orientation) targets
            # -----------------------------------------------------------------
            yaw_class, yaw_res = self.angle2class(gt_bbox[j, 4])
            yaw_class_target[batch_id, 0, cty_int, ctx_int] = yaw_class
            yaw_res_target[batch_id, 0, cty_int, ctx_int] = yaw_res
            # -----------------------------------------------------------------
            # Velocity and brake targets
            # -----------------------------------------------------------------
            velocity_target[batch_id, 0, cty_int, ctx_int] = gt_bbox[j, 5]
            brake_target[batch_id, 0, cty_int, ctx_int] = gt_bbox[j, 6].long()
            # -----------------------------------------------------------------
            # Offset target (sub-pixel correction)
            # -----------------------------------------------------------------
            offset_target[batch_id, 0, cty_int, ctx_int] = ctx - ctx_int
            offset_target[batch_id, 1, cty_int, ctx_int] = cty - cty_int
            # Mark this location as valid for loss computation
            wh_offset_target_weight[batch_id, :, cty_int, ctx_int] = 1
    # ---------------------------------------------------------------------
    # Compute normalization factor (number of positive centers)
    # ---------------------------------------------------------------------
    avg_factor = max(1, center_heatmap_target.eq(1).sum())
    # ---------------------------------------------------------------------
    # Pack all targets into a dictionary
    # ---------------------------------------------------------------------
    target_result = dict(center_heatmap_target=center_heatmap_target,
                         wh_target=wh_target,yaw_class_target=yaw_class_target.squeeze(1),
                         yaw_res_target=yaw_res_target,offset_target=offset_target,
                         velocity_target=velocity_target,brake_target=brake_target.squeeze(1),
                         wh_offset_target_weight=wh_offset_target_weight
                         )
    return target_result, avg_factor

# -------------------------------------------------------------------------
# Convert network predictions → final bounding boxes
# -------------------------------------------------------------------------
def get_bboxes(self,center_heatmap_preds,wh_preds,offset_preds,yaw_class_preds,yaw_res_preds,
               velocity_preds,brake_preds,rescale=True,with_nms=False
               ):
    """
    Decode model outputs into final bounding box predictions.
    This function takes raw predictions from the network and converts them
    into human-interpretable detections (bounding boxes + labels).
    Args:
        center_heatmap_preds (list[Tensor]):
            Predicted heatmaps (B, num_classes, H, W)
        wh_preds (list[Tensor]):
            Predicted width & height (B, 2, H, W)
        offset_preds (list[Tensor]):
            Predicted offsets (B, 2, H, W)
        yaw_class_preds (list[Tensor]):
            Predicted yaw class (orientation bin)
        yaw_res_preds (list[Tensor]):
            Predicted yaw residual
        velocity_preds (list[Tensor]):
            Predicted velocity
        brake_preds (list[Tensor]):
            Predicted brake state (binary classification)
        rescale (bool):
            Whether to map boxes back to original image space
        with_nms (bool):
            Whether to apply Non-Maximum Suppression (NMS)
    Returns:
        list[tuple[Tensor, Tensor]]:
            For each image:
                - det_bboxes: (N, 5) → [x1, y1, x2, y2, score]
                - det_labels: (N,) → class labels
    """
    # ---------------------------------------------------------------------
    # implementation assumes single feature level
    # ---------------------------------------------------------------------
    assert len(center_heatmap_preds) == len(wh_preds) == len(offset_preds) == 1
    # ---------------------------------------------------------------------
    # Decode heatmap predictions into bounding boxes
    # This step:
    # 1. Finds top-K peaks in heatmap (object centers)
    # 2. Uses wh + offset to compute bounding boxes
    # 3. Decodes yaw, velocity, brake
    # ---------------------------------------------------------------------
    batch_det_bboxes, batch_labels = self.decode_heatmap(center_heatmap_preds[0],
                                                         wh_preds[0],offset_preds[0],
                                                         yaw_class_preds[0],yaw_res_preds[0],
                                                         velocity_preds[0], brake_preds[0],
                                                         # Number of top detections to keep
                                                         k=self.train_cfg.top_k_center_keypoints,
                                                         # Kernel size for local max pooling (peak detection)
                                                         kernel=self.train_cfg.center_net_max_pooling_kernel
                                                         )
    # ---------------------------------------------------------------------
    # Apply Non-Maximum Suppression (NMS) removes overlapping duplicate detections
    # ---------------------------------------------------------------------
    if with_nms:
        det_results = []
        for (det_bboxes, det_labels) in zip(batch_det_bboxes, batch_labels):
            # Apply NMS per image
            det_bbox, det_label = self._bboxes_nms(det_bboxes,det_labels,self.test_cfg)
            det_results.append((det_bbox, det_label))
    else:
        # Directly return decoded results (no NMS)
        det_results = [tuple(bs) for bs in zip(batch_det_bboxes, batch_labels)]
    # Return list of detections per image
    return det_results

# -------------------------------------------------------------------------
# Decode network outputs → raw detections (before NMS)
# -------------------------------------------------------------------------
def decode_heatmap(self,center_heatmap_pred,wh_pred,offset_pred,yaw_class_pred,
                   yaw_res_pred,velocity_pred,brake_pred,k=100,kernel=3):
    """
    Convert model predictions into raw bounding box detections.
    This is the core inference logic of CenterNet-style models.
    Steps:
        1. Find local peaks in heatmap (object centers)
        2. Select top-K keypoints
        3. Gather corresponding features (wh, offset, yaw, etc.)
        4. Decode final bounding boxes and attributes
    Args:
        center_heatmap_pred (Tensor):
            Heatmap predictions (B, num_classes, H, W)
        wh_pred (Tensor):
            Width & height predictions (B, 2, H, W)
        offset_pred (Tensor):
            Offset predictions (B, 2, H, W)
        yaw_class_pred (Tensor):
            Yaw classification logits
        yaw_res_pred (Tensor):
            Yaw residual predictions
        velocity_pred (Tensor):
            Velocity predictions
        brake_pred (Tensor):
            Brake classification logits
        k (int):
            Number of top detections to keep
        kernel (int):
            Kernel size for local max pooling
    Returns:
        batch_bboxes (Tensor):
            Shape (B, k, 8) →
            [x, y, w, h, yaw, velocity, brake, score]
        batch_topk_labels (Tensor):
            Class labels for each detection (B, k)
    """
    # ---------------------------------------------------------------------
    # Extract local peaks (non-maximum suppression on heatmap) keeps only local maxima (potential object centers)
    # ---------------------------------------------------------------------
    center_heatmap_pred = get_local_maximum(center_heatmap_pred,kernel=kernel)
    # ---------------------------------------------------------------------
    # Select top-K highest scoring points
    # ---------------------------------------------------------------------
    *batch_dets, topk_ys, topk_xs = get_topk_from_heatmap(center_heatmap_pred,k=k)
    # Extract:
    # - scores → confidence
    # - index → location indices
    # - labels → class IDs
    batch_scores, batch_index, batch_topk_labels = batch_dets
    # ---------------------------------------------------------------------
    # Gather corresponding features at top-K locations
    # ---------------------------------------------------------------------
    wh = transpose_and_gather_feat(wh_pred, batch_index)
    offset = transpose_and_gather_feat(offset_pred, batch_index)
    yaw_class = transpose_and_gather_feat(yaw_class_pred, batch_index)
    yaw_res = transpose_and_gather_feat(yaw_res_pred, batch_index)
    velocity = transpose_and_gather_feat(velocity_pred, batch_index)
    brake = transpose_and_gather_feat(brake_pred, batch_index)
    # Convert brake logits → class (0 or 1)
    brake = torch.argmax(brake, -1)
    # Extract scalar velocity
    velocity = velocity[..., 0]
    # ---------------------------------------------------------------------
    # Decode yaw (orientation)
    # ---------------------------------------------------------------------
    # Convert yaw logits → class index
    yaw_class = torch.argmax(yaw_class, -1)
    # Convert (class + residual) → continuous angle
    yaw = self.class2angle(yaw_class,yaw_res.squeeze(2))
    # ---------------------------------------------------------------------
    # Refine center coordinates using offset
    # ---------------------------------------------------------------------
    topk_xs = topk_xs + offset[..., 0]
    topk_ys = topk_ys + offset[..., 1]
    # ---------------------------------------------------------------------
    # Construct bounding boxes
    # Format:[center_x, center_y, width, height, yaw, velocity, brake]
    # ---------------------------------------------------------------------
    batch_bboxes = torch.stack([topk_xs,topk_ys,wh[..., 0],wh[..., 1],yaw,
                                velocity,brake],dim=2)
    # Append confidence score
    batch_bboxes = torch.cat((batch_bboxes, batch_scores[..., None]),dim=-1)
    # ---------------------------------------------------------------------
    # Rescale boxes to original image resolution(feature map → image space)
    # ---------------------------------------------------------------------
    ratio = 4.0
    batch_bboxes[:, :, :4] *= ratio
    # Return:
    # - bounding boxes with attributes
    # - class labels
    return batch_bboxes, batch_topk_labels

# -------------------------------------------------------------------------
# Apply Non-Maximum Suppression (NMS) to filter overlapping boxes
# -------------------------------------------------------------------------
def _bboxes_nms(self, bboxes, labels, cfg):
    """
    Perform NMS to remove duplicate/overlapping detections.
    Args:
        bboxes (Tensor):
            Shape (N, 8) → [x, y, w, h, yaw, velocity, brake, score]
        labels (Tensor):
            Shape (N,) → class labels
        cfg:
            Configuration containing:
                - nms_cfg: NMS parameters (IoU threshold, etc.)
                - max_per_img: max detections to keep
    Returns:
        out_bboxes (Tensor):
            Filtered bounding boxes after NMS
        out_labels (Tensor):
            Corresponding class labels
    """
    # ---------------------------------------------------------------------
    # Edge case: no detections
    # ---------------------------------------------------------------------
    if labels.numel() == 0:
        return bboxes, labels
    # ---------------------------------------------------------------------
    # Apply batched NMS
    # Inputs:
    # - boxes → only first 4 values (x, y, w, h or x1, y1, x2, y2)
    # - scores → last value in bbox tensor
    # - labels → used to perform class-wise NMS
    # ---------------------------------------------------------------------
    out_bboxes, keep = batched_nms(
        bboxes[:, :4].contiguous(),     # box coordinates
        bboxes[:, -1].contiguous(),     # confidence scores
        labels,                         # class labels
        cfg.nms_cfg                     # NMS configuration
    )
    # Keep corresponding labels
    out_labels = labels[keep]
    # ---------------------------------------------------------------------
    # Limit number of detections per image
    # ---------------------------------------------------------------------
    if len(out_bboxes) > 0:
        # Sort detections by score (descending)
        idx = torch.argsort(out_bboxes[:, -1], descending=True)
        # Keep only top-K detections
        idx = idx[:cfg.max_per_img]
        out_bboxes = out_bboxes[idx]
        out_labels = out_labels[idx]
    # Return filtered detections
    return out_bboxes, out_labels

# -------------------------------------------------------------------------
# LidarCenterNet: Multi-task perception + prediction network
# -------------------------------------------------------------------------
class LidarCenterNet(nn.Module):
    """
    Main model for LiDAR-based perception and trajectory prediction.

    This model combines:
    - Multi-modal backbone (LiDAR + Image)
    - Perception heads (segmentation, depth, detection)
    - Motion prediction (waypoints using GRU)
    Args:
        config: Configuration object (hyperparameters, settings)
        device: CPU or GPU device
        backbone: Backbone network reference
        image_architecture (str): Image encoder type (default: resnet34)
        lidar_architecture (str): LiDAR encoder type (default: resnet18)
        estimate_loss (bool): Whether to compute training loss
    """
    def __init__(self,config,device,backbone,image_architecture='resnet34',
                 lidar_architecture='resnet18',estimate_loss=True):
        super().__init__()
        # -----------------------------------------------------------------
        # Basic settings
        # -----------------------------------------------------------------
        self.device = device
        self.config = config
        self.estimate_loss = estimate_loss
        # Number of future waypoints to predict
        self.pred_len = config.pred_len
        # Whether to use target point information
        self.use_target_point_image = config.use_target_point_image
        self.gru_concat_target_point = config.gru_concat_target_point
        # External backbone reference
        self.backbone = backbone
        # -----------------------------------------------------------------
        # Multi-modal backbone (LiDAR + Image fusion)
        # -----------------------------------------------------------------
        self._model = TransfuserBackbone(config,image_architecture,lidar_architecture).to(self.device)
        # -----------------------------------------------------------------
        # Perception decoders
        # -----------------------------------------------------------------
        # Semantic segmentation decoder
        self.seg_decoder = SegDecoder(self.config,self.config.perception_output_features).to(self.device)
        # Depth estimation decoder
        self.depth_decoder = DepthDecoder(self.config,self.config.perception_output_features).to(self.device)
        # -----------------------------------------------------------------
        # BEV (Bird’s Eye View) prediction head
        # -----------------------------------------------------------------
        channel = config.channel
        self.pred_bev = nn.Sequential(# Feature refinement
                                      nn.Conv2d(channel, channel, kernel_size=3, stride=1, padding=1),
                                      nn.ReLU(inplace=True),
                                      # Output BEV map (3 channels)
                                      nn.Conv2d(channel, 3, kernel_size=1, stride=1, padding=0)).to(self.device)
        # -----------------------------------------------------------------
        # Detection head (CenterNet-based)
        # -----------------------------------------------------------------
        self.head = LidarCenterNetHead(channel,channel,1,train_cfg=config).to(self.device)
        # -----------------------------------------------------------------
        # Waypoint prediction (trajectory planning)
        # -----------------------------------------------------------------
        # Fully connected layers to process global features
        self.join = nn.Sequential(nn.Linear(512, 256),nn.ReLU(inplace=True),nn.Linear(256, 128),
                                  nn.ReLU(inplace=True),nn.Linear(128, 64),nn.ReLU(inplace=True)).to(self.device)
        # GRU-based sequential decoder
        self.decoder = nn.GRUCell(input_size=4 if self.gru_concat_target_point else 2,
                                  hidden_size=self.config.gru_hidden_size).to(self.device)
        # Global feature pooling
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        # Final output layer
        # Predicts: (x, y, maybe orientation or velocity)
        self.output = nn.Linear(self.config.gru_hidden_size,3).to(self.device)

# -------------------------------------------------------------------------
# GRU-based waypoint prediction (trajectory generation)
# -------------------------------------------------------------------------
def forward_gru(self, z, target_point):
    """
    Predict future waypoints using an autoregressive GRU.
    This function generates a sequence of future positions (waypoints)
    based on encoded features and an optional target point.
    Args:
        z (Tensor):
            Global feature vector (B, feature_dim)
        target_point (Tensor):
            Target destination point (B, 2)
    Returns:
        pred_wp (Tensor):
            Predicted waypoints (B, pred_len, 2)
    """
    # ---------------------------------------------------------------------
    # Process global features through MLP
    # ---------------------------------------------------------------------
    z = self.join(z)
    # Store predicted waypoints
    output_wp = list()
    # ---------------------------------------------------------------------
    # Initialize GRU input start from origin (0,0) in vehicle coordinate system
    # ---------------------------------------------------------------------
    x = torch.zeros(size=(z.shape[0], 2),dtype=z.dtype).to(z.device)
    # ---------------------------------------------------------------------
    # Prepare target point flip y-axis (coordinate system adjustment)
    # ---------------------------------------------------------------------
    target_point = target_point.clone()
    target_point[:, 1] *= -1
    # ---------------------------------------------------------------------
    # Autoregressive waypoint generation
    # ---------------------------------------------------------------------
    for _ in range(self.pred_len):
        # Optionally concatenate target point with current position
        if self.gru_concat_target_point:
            x_in = torch.cat([x, target_point], dim=1)
        else:
            x_in = x
        # Update hidden state using GRU
        z = self.decoder(x_in, z)
        # Predict displacement (dx, dy, ...)
        dx = self.output(z)
        # Update current position (accumulate displacement)
        x = dx[:, :2] + x
        # Store predicted waypoint
        output_wp.append(x[:, :2])
    # ---------------------------------------------------------------------
    # Stack waypoints into sequence shape: (B, pred_len, 2)
    # ---------------------------------------------------------------------
    pred_wp = torch.stack(output_wp, dim=1)
    # ---------------------------------------------------------------------
    # Convert coordinate system Vehicle → LiDAR coordinates (because GT waypoints are in LiDAR frame)
    # ---------------------------------------------------------------------
    pred_wp[:, :, 0] = pred_wp[:, :, 0] - self.config.lidar_pos[0]
    # Return predicted trajectory
    return pred_wp

# -------------------------------------------------------------------------
# Forward pass of LidarCenterNet (full pipeline)
# -------------------------------------------------------------------------
def forward(self, data):
    """
    Main forward function of the model.
    This performs:
        - Multi-modal feature extraction (LiDAR + RGB)
        - Waypoint prediction (trajectory)
        - BEV prediction
        - Semantic segmentation & depth estimation
        - 3D object detection
        - Loss computation (if training)
    Args:
        data (dict):
            Input dictionary containing:
                - rgb: camera images
                - lidar: LiDAR BEV input
                - target_point_image: target point encoded as image
                - speed: vehicle speed
                - target_point: navigation target
                - bev, semantic, depth: ground truth labels
                - label: bounding box annotations
    Returns:
        loss (dict): All computed losses (if training)
        debug_outputs (dict): Optional debug outputs
    """
    # Initialize loss dictionary
    loss = {}
    # ---------------------------------------------------------------------
    # Prepare LiDAR input concatenate LiDAR BEV with target point image
    # ---------------------------------------------------------------------
    data['lidar'] = torch.cat((data['lidar'], data['target_point_image']),dim=1)
    # ---------------------------------------------------------------------
    # Extract features using multi-modal backbone
    # ---------------------------------------------------------------------
    features, image_features_grid, fused_features = self._model(data['rgb'],data['lidar'],data['speed'])
    # ---------------------------------------------------------------------
    # Predict future waypoints (trajectory)
    # ---------------------------------------------------------------------
    pred_wp = self.forward_gru(fused_features,data['target_point'])
    # ---------------------------------------------------------------------
    # Predict BEV (Bird’s Eye View)
    # ---------------------------------------------------------------------
    pred_bev = self.pred_bev(features[0])
    # Upsample to desired BEV resolution
    pred_bev = F.interpolate(pred_bev,(self.config.bev_resolution_height,
                                       self.config.bev_resolution_width),
                             mode='bilinear',align_corners=True)
    # ---------------------------------------------------------------------
    # Semantic segmentation & depth prediction
    # ---------------------------------------------------------------------
    pred_semantic = self.seg_decoder(image_features_grid)
    pred_depth = self.depth_decoder(image_features_grid)
    # ---------------------------------------------------------------------
    # 3D object detection (CenterNet head)
    # ---------------------------------------------------------------------
    preds = self.head([features[0]])
    # Decode detections (no gradient needed)
    with torch.no_grad():
        results = self.head.get_bboxes(preds[0], preds[1], preds[2],
                                       preds[3], preds[4], preds[5], preds[6])
        # Convert detections to numpy
        batch_detections = [x[0].detach().cpu().numpy() for x in results]
        # Filter by confidence threshold
        batch_detections = [x[x[:, -1] > self.config.bb_confidence_threshold][:, :7] for x in batch_detections]
    # ---------------------------------------------------------------------
    # Compute losses (only during training)
    # ---------------------------------------------------------------------
    if self.estimate_loss:
        # ---------------- BEV loss ----------------
        weight = torch.from_numpy(np.array([1., 1., 3.])).to(dtype=torch.float32, device=pred_bev.device)
        loss_bev = F.cross_entropy(pred_bev,data['bev'],weight=weight).mean()
        # ---------------- Waypoint loss ----------------
        loss_wp = torch.mean(torch.abs(pred_wp - data['ego_waypoint']))
        loss.update({"loss_wp": loss_wp,"loss_bev": loss_bev})
        # ---------------- Detection loss ----------------
        # Dummy labels (single-class setup)
        gt_labels = torch.zeros_like(data['label'][:, :, 0])
        # Ignore empty boxes
        gt_bboxes_ignore = data['label'].sum(dim=-1) == 0.
        loss_bbox = self.head.loss(preds[0], preds[1], preds[2],preds[3],
                                   preds[4], preds[5], preds[6],[data['label']],
                                   gt_labels=[gt_labels],gt_bboxes_ignore=[gt_bboxes_ignore],
                                   img_metas=None)
        loss.update(loss_bbox)
        # ---------------- Semantic segmentation loss ----------------
        loss_semantic = self.config.ls_seg * F.cross_entropy(pred_semantic,data['semantic']).mean()
        # ---------------- Depth loss ----------------
        loss_depth = self.config.ls_depth * F.l1_loss(pred_depth,data['depth']).mean()
        loss.update({"loss_depth": loss_depth,"loss_semantic": loss_semantic})
    else:
        # No loss computation (inference mode)
        pass
    # ---------------------------------------------------------------------
    # Debug outputs
    # ---------------------------------------------------------------------
    if self.config.debug:
        debug_outputs = {'pred_wp': pred_wp.detach().cpu().numpy(),
                         'pred_semantic': pred_semantic.detach().cpu().numpy(),
                         'pred_depth': pred_depth.detach().cpu().numpy(),
                         'detections': batch_detections,
                         'pred_bev': pred_bev.detach().cpu().numpy()
                         }
    else:
        debug_outputs = {}
    # ---------------------------------------------------------------------
    # Return losses and debug outputs
    # ---------------------------------------------------------------------
    return loss, debug_outputs

