# -*- coding: utf-8 -*-
"""transfuser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UgGbE13YTpiHIJIw_7T97fIEFtLI5ogf
"""

# provides access to mathematical functions like sqrt, log, etc.
import math
# main PyTorch library used for tensor computations and deep learning
import torch
# imports neural network module (layers like Linear, Conv2d, etc.)
from torch import nn
# functional API for operations like activation functions (ReLU, softmax), loss functions, etc.
import torch.nn.functional as F
# pyTorch Image Models library — provides pre-trained models (ResNet, ViT, EfficientNet, etc.)
import timm

class TransfuserBackbone(nn.Module):
    """
    Multi-scale Fusion Transformer for image + LiDAR feature fusion

    image_architecture: Architecture used in the image branch
                        (e.g., ResNet, RegNet, ConvNeXt)

    lidar_architecture: Architecture used in the LiDAR branch
                        (e.g., ResNet, RegNet, ConvNeXt)
    """

    def __init__(self, config, image_architecture='resnet34', lidar_architecture='resnet18'):
        # intialize parent class (nn.Module)
        super().__init__()

        # store configuration (contains hyperparameters like feature sizes, anchors, etc.)
        self.config = config

        # ---------------- Image Branch ----------------
        # adaptive pooling resizes features maps to a fixed spatial size regardless of input resolution
        # this creates a fixed grid of "token" for transformer fusion
        self.avgpool_img = nn.AdaptiveAvgPool2d(
            (self.config.img_vert_anchors, self.config.img_horz_anchors)
        )

        # ---------------- LiDAR Branch ----------------
        # same idea for LiDAR features → convert to fixed-size representation important because LiDAR Bird Eye view maps vary in resolution
        self.avgpool_lidar = nn.AdaptiveAvgPool2d(
            (self.config.lidar_vert_anchors, self.config.lidar_horz_anchors)
        )

        # ---------------- Image Encoders----------------
        # backbone network (ResNet34 by default)
        self.image_encoder = ImageCNN(
            architecture=image_architecture,
            # normalize input images (important for pretrained models)
            normalize=True,
            # output feature dimension (shared with LiDAR branch for fusion)
            out_features=self.config.perception_output_features
        )

        # ---------------- LiDAR Encoder----------------
        # Input channels for LiDAR:
        # 2 * lidar_seq_len → typically x,y or BEV features over time (temporal stacking)
        # +1 → extra channel for target point (goal location encoded in image space)
        in_channels = (2 * config.lidar_seq_len) + 1
        self.lidar_encoder = LidarEncoder(
            # backbone network (ResNet18 by default)
            architecture=lidar_architecture,
            # custom input channels (LiDAR is not RGB → must define manually)
            in_channels=in_channels,
            # match output dimension with image encoder for fusion
            out_features=self.config.perception_output_features
        )

        # ---------------- Fusion Transformers Block ----------------
        # embedding dimension (feature size per token) taken from image encoder intermediate features
        # map channels ensures transfromer input matches CNN featues depth
        self.transformer1 = GPT(
            n_embd=self.image_encoder.features.feature_info[1]['num_chs'],
            # number of attention heads in Multi-Head Self-Attention
            # more heads → better ability to capture different relationships
            n_head=config.n_head,
            # expansion factor in feed-forward (MLP) layer inside transformer
            # controls hidden layer size (usually 2x–4x of embedding dim)
            block_exp=config.block_exp,
            # number of transformer layers stacked
            # more layers → deeper feature interaction (but higher compute)
            n_layer=config.n_layer,
            # spatial grid size for image features defines how image feature map is split into tokens
            img_vert_anchors=config.img_vert_anchors,
            img_horz_anchors=config.img_horz_anchors,
            # same grid concept for LiDAR BEV features important for aligning spatial correspondence
            lidar_vert_anchors=config.lidar_vert_anchors,
            lidar_horz_anchors=config.lidar_horz_anchors,
            # total number of tokens passed to transformer =
            # = (image tokens + lidar tokens + possibly temporal tokens)
            seq_len=config.seq_len,
            # dropout applied on embedding (input tokens) helps prevent overfitting
            embd_pdrop=config.embd_pdrop,
            # dropout inside attention mechanism regularizes attention weights
            attn_pdrop=config.attn_pdrop,
            #  dropout  on residual connections stabilizes deep transformer training
            resid_pdrop=config.resid_pdrop,
            # full config passed for additional settings or flexibility
            config=config
        )

        # ---------------- Second Fusion Transformer (Deeper Sacle)----------------
        self.transformer2 = GPT(
            # embedding dimension taken from a deeper layer of the image encoder feature_info[2] → deeper than [1], so:
            # - more semantic (object-level understanding) & less spatial detail
            n_embd=self.image_encoder.features.feature_info[2]['num_chs'],
            # number of attention heads for multi-head self-attention
            n_head=config.n_head,
            # expansion ratio for feed-forward network inside transformer block
            block_exp=config.block_exp,
            # number of stacked transformer layers
            n_layer=config.n_layer,
            # defines how image feature maps are divided into tokens (grid size)
            img_vert_anchors=config.img_vert_anchors,
            img_horz_anchors=config.img_horz_anchors,
            # same grid/tokenization for LiDAR features
            lidar_vert_anchors=config.lidar_vert_anchors,
            lidar_horz_anchors=config.lidar_horz_anchors,
            # total sequence length (image tokens + LiDAR tokens)
            seq_len=config.seq_len,
            # droupout applied to input embeddings
            embd_pdrop=config.embd_pdrop,
            # dropout inside attention mechanism
            attn_pdrop=config.attn_pdrop,
            # dropout applied on residual connections
            resid_pdrop=config.resid_pdrop,
            # full configuration object for additional flexibility
            config=config
        )

        # ----------------- Third Fusion Transformer (Deepest / Semantic Level)----------------
        self.transformer3 = GPT(
            # embedding dimension from an even deeper CNN layer feature_info[3] → very deep features:
            # 1.highly semantic (object/category-level understanding)
            # 2. very low spatial resolution
            n_embd=self.image_encoder.features.feature_info[3]['num_chs'],
            # number of attention heads (parallel attention mechanisms)
            n_head=config.n_head,
            # expansion factor for feed-forward layers inside transformer
            block_exp=config.block_exp,
            # number of transformer blocks stacked depth of reasoning
            n_layer=config.n_layer,
            # defines spatial grid for image tokens
            img_vert_anchors=config.img_vert_anchors,
            img_horz_anchors=config.img_horz_anchors,
            # defines spatial grid for LiDAR tokens (BEV representation)
            lidar_vert_anchors=config.lidar_vert_anchors,
            lidar_horz_anchors=config.lidar_horz_anchors,
            # total numbef of tokens (image + LiDAR)
            seq_len=config.seq_len,
            # dropout on input embedding
            embd_pdrop=config.embd_pdrop,
            attn_pdrop=config.attn_pdrop,
            # droupout on residual connections
            resid_pdrop=config.resid_pdrop,
            # full configuration object
            config=config
        )

        # ----------------- Fourth Fusion Transformer (Deepest & Global Contest Level) --------------
        self.transformer4 = GPT(
            # embedding dimension from the deepest CNN layer  feature_info[4] → final stage of backbone:
            # 1. maximum semantic abstraction
            # 2. minimal spatial resolution
            # 3. captures global scene context
            n_embd=self.image_encoder.features.feature_info[4]['num_chs'],
            # number of attention heads for multi-head attention
            n_head=config.n_head,
            # expansion ratio for feed-forward network inside transformer
            block_exp=config.block_exp,
            # number of stacked transformer layers
            n_layer=config.n_layer,
            # grid size for image features tokenization
            img_vert_anchors=config.img_vert_anchors,
            img_horz_anchors=config.img_horz_anchors,
            # grid size for LiDAR feature tokenization
            lidar_vert_anchors=config.lidar_vert_anchors,
            lidar_horz_anchors=config.lidar_horz_anchors,
            # total number of tokens (image + LiDAR combined)
            seq_len=config.seq_len,
            # dropout applied to embedding
            embd_pdrop=config.embd_pdrop,
            # dropout inside attention computation
            attn_pdrop=config.attn_pdrop,
            # dropout on residual connections
            resid_pdrop=config.resid_pdrop,
            # full configuration object
            config=config
        )

        # ---------------- Channel Alignment (Final Features Stage) ----------------
        # Check if the number of channels from the deepest CNN layer matches the required perception output feature size
        # if not equal -> need to convert (project) channels
        if (self.image_encoder.features.feature_info[4]['num_chs'] != self.config.perception_output_features):
            self.change_channel_conv_image = nn.Conv2d(
                # input channels from image backbone (deepest layer)
                self.image_encoder.features.feature_info[4]['num_chs'],
                # desired output feature dimension (common fusion size)
                self.config.perception_output_features,
                # 1x1 convolution → channel projection only (no spatial change)
                (1, 1)
            )
            self.change_channel_conv_lidar = nn.Conv2d(
                # input channels for LiDAR backbone
                self.image_encoder.features.feature_info[4]['num_chs'],
                # same  target feature dimension must match image branch
                self.config.perception_output_features,
                #  1x1 convolution for channel alignment
                (1, 1)
            )
        else:
            # if channels already match → no transformation needed
            # - identity mapping (does nothing)
            self.change_channel_conv_image = nn.Sequential()
            # - identity mapping (does nothing)
            self.change_channel_conv_lidar = nn.Sequential()

        # ---------------- FPN(Features Pyramid Network) Fusion ----------------
        # number of channels used in BEV (Bird’s Eye View) feature maps this unified feature dimension for pyramid fusion
        channel = self.config.bev_features_chanels
        # activation function (inplace = True saves memory)
        self.relu = nn.ReLU(inplace=True)

        # ---------------- Top-Down Pathway----------------
        # upsapling layer used to increase spatial resolution of deeper features
        # this is the core of FPN: bringing low-resolution (deep) features to higher resolution
        self.upsample = nn.Upsample(
            scale_factor=self.config.bev_upsample_factor,
            mode='bilinear',
            align_corners=False
        )
        #  1x1 convolution to refine/up-project features from deepest level (C5) helps align features after upsampling
        self.up_conv5 = nn.Conv2d(channel, channel, (1, 1))
        # same for next level (C4)
        self.up_conv4 = nn.Conv2d(channel, channel, (1, 1))
        # same for next level (C3)
        self.up_conv3 = nn.Conv2d(channel, channel, (1, 1))

        # ---------------- LATERAL CONNECTION ----------------
        # converts backbone features (C5 level) into FPN feature space
        # this allows combining top-down features with corresponding bottom-up features
        self.c5_conv = nn.Conv2d(
            # input channels from backbone (output of transformer/CNN)
            self.config.perception_output_features,
            # convert to Bird Eye View Featues channels
            channel,
            # 1x1 convolution for channel alignment
            (1, 1)
        )

    def top_down(self, x):
        # convert deepest backbone features (C5) → FPN feature space
        # apply 1x1 conv for channel alignment + ReLU activation
        # p5 = highest semantic, lowest resolution
        # ---------------- C5 → P5 ----------------
        p5 = self.relu(self.c5_conv(x))
        # upsample p5 to match spatial size of next level (C4 scale)
        # apply 1x1 conv to refine features
        # p4 = slightly higher resolution, still strong semantics
        # ---------------- P5 → P4 ----------------
        p4 = self.relu(self.up_conv5(self.upsample(p5)))
        # ---------------- P4 → P3 ------------------
        # Repeat: upsample + refine
        #  p3 = medium resolution + balanced semantic/detail info
        p3 = self.relu(self.up_conv4(self.upsample(p4)))
        #  ---------------- P3 → P2 ----------------
        # final upsampling stage
        #  p2 = highest resolution, best for fine spatial details
        p2 = self.relu(self.up_conv3(self.upsample(p3)))
        # ---------------- Ouput----------------
        # Return full feature pyramid:
        # 1. p2 → finest resolution (localization)
        # 2. p3 → mid-level
        # 3. p4 → coarse
        # 4. p5 → deepest semantic features
        return p2, p3, p4, p5

    def forward(self, image, lidar, velocity):
        '''
        Image + LiDAR feature fusion using transformers
        Args:
            image_list (list): list of input images
            lidar_list (list): list of input LiDAR BEV
            velocity (tensor): input velocity from speedometer
        '''
        # ---------------- Image Preprocessing----------------
        # normalize  image using ImageNet statistics (mean & std) required  when using pretrained CNN backbones
        # (ResNet, ConvNeXt, etc.) ensures input distribution matches training distribution
        if self.image_encoder.normalize:
            image_tensor = normalize_imagenet(image)
        else:
            # if normalization is disabled use raw image directly
            image_tensor = image

        # ---------------- LiDAR Preprocessing ----------------
        #  Assign LiDAR input (typically BEV representation) no normalization here because:
        # - LiDAR data is already structured (e.g., occupancy, height, intensity)
        # - distribution is different from RGB images
        lidar_tensor = lidar

        # ---------------- Initial Features Extraction ----------------
        # ----- (1) Image Branch -----
        # first convolution layer (large receptive field) extracts low-level features like edges, textures
        image_features = self.image_encoder.features.conv1(image_tensor)
        # batch normalization -> stabilizes training and normalizes feature distribution
        image_features = self.image_encoder.features.bn1(image_features)
        # activation function (usually ReLU) adds non-linearity allow learning complex pattern
        image_features = self.image_encoder.features.act1(image_features)
        # downsamples spatial resolution (H, W ↓) keeps important features while reducing computation
        image_features = self.image_encoder.features.maxpool(image_features)
        # ----- (2) LiDAR Branch-----
        # first convolution for LiDAR BEV input extracts basic spatial patterns (occupancy, geometry)
        lidar_features = self.lidar_encoder._model.conv1(lidar_tensor)
        # normalize LiDAR features maps
        lidar_features = self.lidar_encoder._model.bn1(lidar_features)
        # non-linear activation
        lidar_features = self.lidar_encoder._model.act1(lidar_features)
        # downsampling → reduces resolution, increases receptive field
        lidar_features = self.lidar_encoder._model.maxpool(lidar_features)

        # ---------------- First Residual Block (Layer 1)----------------
        # first ResNet block:
        # - captures slightly higher-level features (edges → shapes)
        # - still high spatial resolution
        image_features = self.image_encoder.features.layer1(image_features)
        # same operation for LiDAR branch learns structured spatial patterns in BEV (lanes, obstacles, clusters)
        lidar_features = self.lidar_encoder._model.layer1(lidar_features)

        # ----------------Multi-model Fusion (layer 1)----------------
        # image feature shape: (B, 72, 40, 176)
        # LiDAR feature shape: (B, 72, 64, 64)
        # ----- 1. Tokenization-----
        # - convert image features → fixed-size tokens (for transformer)
        image_embd_layer1 = self.avgpool_img(image_features)
        # - convert LiDAR BEV features → tokens
        lidar_embd_layer1 = self.avgpool_lidar(lidar_features)
        # ----- 2.Transformer Fusion-----
        # - cross model fusion: image -> LiDAR interaction using attention
        image_features_layer1, lidar_features_layer1 = self.transformer1(
            image_embd_layer1, lidar_embd_layer1
        )
        # ----- 3. Upsample Back to Original Size Upsample-----
        # - restores spatial resolution of fused image features
        image_features_layer1 = F.interpolate(
            image_features_layer1,
            size=(image_features.shape[2], image_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # - restore  spatial resolution of fused LiDAR features
        lidar_features_layer1 = F.interpolate(
            lidar_features_layer1,
            size=(lidar_features.shape[2], lidar_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # ----- 4. Residual Fusion -----
        # inject fused information into original image features
        image_features = image_features + image_features_layer1
        # inject fused information into LiDAR features
        lidar_features = lidar_features + lidar_features_layer1

        # ---------------- Deeper Features Extraction (Layer 2) ----------------
        # pass fused image features into next CNN block (Layer2) learns higher-level patterns (shapes → objects)
        image_features = self.image_encoder.features.layer2(image_features)
        # same for LiDAR : learns more structured spatial understanding in BEV
        lidar_features = self.lidar_encoder._model.layer2(lidar_features)

        # ---------------- Multi-model Fusion(layer 2 - Mid Level) ----------------
        # image feature shape example: (B, 216, 20, 88)
        # LiDAR feature shape example: (B, 216, 32, 32)
        # ----- 1. Tokenization-----
        # - convert image feature map → fixed-size tokens for transformer
        image_embd_layer2 = self.avgpool_img(image_features)
        # convert LiDAR BEV features → tokens
        lidar_embd_layer2 = self.avgpool_lidar(lidar_features)
        # ----- 2. Transformer Fusion-----
        # cross-modal attention at a deeper level:
        # - stronger semantic understanding than layer1
        # - better object-level alignment (cars, pedestrians, lanes)
        image_features_layer2, lidar_features_layer2 = self.transformer2(
            image_embd_layer2, lidar_embd_layer2
        )
        # ----- 3.Upsample back to original resolution  -----
        # restore spatial resolution for image features
        image_features_layer2 = F.interpolate(
            image_features_layer2,
            size=(image_features.shape[2], image_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # restore spatial resolution for LiDAR features
        lidar_features_layer2 = F.interpolate(
            lidar_features_layer2,
            size=(lidar_features.shape[2], lidar_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )

        # ----- 4. Residual Fusion-----
        # add fused features → enrich image representation
        image_features = image_features + image_features_layer2
        # add fused features → enrich LiDAR representation
        lidar_features = lidar_features + lidar_features_layer2

        # ---------------- Deep Feature Extraction (layer 3) ----------------
        # Pass fused image features into deeper CNN block (Layer3) learns high-level semantics:
        # - object identity
        # - scene structure
        image_features = self.image_encoder.features.layer3(image_features)
        # same for LiDAR: learns structured 3D relationships in BEV space
        lidar_features = self.lidar_encoder._model.layer3(lidar_features)

        # ---------------- Multi-Model Fusion (LAYER 3 - HIGH LEVEL) ----------------
        # image feature shape example: (B, 576, 10, 44)
        # LiDAR feature shape example: (B, 576, 16, 16)
        # ----- 1. Tokenization -----
        # convert deep image features → fixed-size tokens for transformer
        image_embd_layer3 = self.avgpool_img(image_features)
        # convert deep LiDAR BEV features → tokens
        lidar_embd_layer3 = self.avgpool_lidar(lidar_features)
        # ----- 2. Transformer Fusion-----
        # cross-modal attention at a deeper semantic level:
        # - focuses on object relationships
        # - captures scene-level understanding (cars, lanes, layout)
        image_features_layer3, lidar_features_layer3 = self.transformer3(
            image_embd_layer3, lidar_embd_layer3
        )
        # ----- 3.Upsample back to original resolution-----
        # restore spatial resolution for image branch
        image_features_layer3 = F.interpolate(
            image_features_layer3,
            size=(image_features.shape[2], image_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # restore spatial resolution for LiDAR branch
        lidar_features_layer3 = F.interpolate(
            lidar_features_layer3,
            size=(lidar_features.shape[2], lidar_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # ----- 4. Residual Fusion -----
        # inject high-level fused features into image representation
        image_features = image_features + image_features_layer3
        # inject high-level fused features into LiDAR representation
        lidar_features = lidar_features + lidar_features_layer3

        # ---------------- Final Backbone Stage (Layer 4) ----------------
        # final CNN stage for image:
        # - produces deepest features
        # - strong semantic abstraction (scene-level understanding)
        image_features = self.image_encoder.features.layer4(image_features)
        # final CNN stage for LiDAR:
        # - captures global BEV structure
        # - encodes relationships between objects in space
        lidar_features = self.lidar_encoder._model.layer4(lidar_features)

        # ---------------- Multi-Model Fusion (Layer 4: Global & Decision Level) ----------------
        # - image feature shape example: (B, 1512, 5, 22)
        # - LiDAR feature shape example: (B, 1512, 8, 8)
        # ----- 1. Tokenization -----
        # convert deepest image features → fixed-size tokens
        # these features are highly semantic (scene-level understanding)
        image_embd_layer4 = self.avgpool_img(image_features)
        # convert deepest LiDAR BEV features → tokens encodes global spatial structure
        lidar_embd_layer4 = self.avgpool_lidar(lidar_features)
        # ----- 2. Transformer Fusion-----
        # final cross-modal fusion:
        # - integrates global scene context
        # - captures relationships between all objects
        # - prepares features for decision-making
        image_features_layer4, lidar_features_layer4 = self.transformer4(
            image_embd_layer4, lidar_embd_layer4
        )
        # ----- 3. Upsample back to original resolution -----
        # restore spatial resolution for image branch
        image_features_layer4 = F.interpolate(
            image_features_layer4,
            size=(image_features.shape[2], image_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # restore spatial resolution for LiDAR branch
        lidar_features_layer4 = F.interpolate(
            lidar_features_layer4,
            size=(lidar_features.shape[2], lidar_features.shape[3]),
            mode='bilinear',
            align_corners=False
        )
        # ----- 4. Residual Fusion -----
        # add global fused information to image features  → enhances decision-level understanding
        image_features = image_features + image_features_layer4
        # add global fused information to LiDAR features → enriches spatial reasoning with semantic context
        lidar_features = lidar_features + lidar_features_layer4

        # ---------------- Channel Alignment---------------
        # --- Reduce/convert channel dimensions to a fixed size (e.g., 512)----
        # - ensures image features have consistent channel size for fusion/output
        image_features = self.change_channel_conv_image(image_features)
        # - same for LiDAR features → both modalities now aligned
        lidar_features = self.change_channel_conv_lidar(lidar_features)

        # ---------------- Store Intermediate Features  ----------------
        # -save LiDAR feature map (deepest level) for FPN top-down pathway
        x4 = lidar_features
        # preserve spatial image feature map (used for auxiliary tasks like attention/visualization)
        image_features_grid = image_features

        # ---------------- Global Features Extraction  ----------------
        # global average pooling → (B, C, H, W) → (B, C, 1, 1)
        image_features = self.image_encoder.features.global_pool(image_features)
        # Flatten → (B, C) -> converts spatial features into vector representation
        image_features = torch.flatten(image_features, 1)
        # same global pooling for LiDAR features
        lidar_features = self.lidar_encoder._model.global_pool(lidar_features)
        # flatten -> (B, C)
        lidar_features = torch.flatten(lidar_features, 1)

        # ---------------- Final Fusion (Vector Level)----------------
        # combine global representations (late fusion) represents this overall scene
        # understanding (used for control/planning)
        fused_features = image_features + lidar_features

        # ---------------- FPN (Multi-Scale BEV Featues)---------------
        # apply FPN top-down pathway on LiDAR features produces multi-scale BEV featues maps (p2, p3, p4, p5)
        features = self.top_down(x4)

        # ---------------- Output----------------
        #  features → multi-scale BEV features (for detection/planning)
        # image_features_grid → spatial image features (for auxiliary tasks)
        # fused_features → global fused vector (for decision/control)
        return features, image_features_grid, fused_features

class SegDecoder(nn.Module):
    def __init__(self, config, latent_dim=512):
        # intialize parent nn.Module (required for all PyTorch models)
        super().__init__()
        # store configuration object (contains hyperparameters like number of classes, etc.)
        self.config = config
        # dimensionality of input feature vector/map (coming from backbone / fused features)
        # typically matches output channels from encoder (e.g., 512)
        self.latent_dim = latent_dim
        # number of  segmentation classes (e.g., road, vehicle, pedestrian, etc.)
        # determines number of output channels in final segmentation map
        self.num_class = config.num_class

        self.deconv1 = nn.Sequential(
            # First convolution:
            # - input: latent feature map (e.g., 512 channels from backbone)
            # - output: reduced channels (deconv_channel_num_1)
            # - Kernel=3, stride=1, padding=1 → keeps spatial size unchanged
            # purpose: start transforming high-level features into decoder space
            nn.Conv2d(self.latent_dim, self.config.deconv_channel_num_1, 3, 1, 1),
            # activation funstion (ReLU) inplace=True → saves memory by modifying tensor directly
            nn.ReLU(True),
            # Second convolution:
            # - further reduces or reshapes channel dimensions
            # - learns more refined feature representations
            # - still preserves spatial resolution
            nn.Conv2d(self.config.deconv_channel_num_1, self.config.deconv_channel_num_2, 3, 1, 1),
            # activation -> introduces non-linearity for better learning
            nn.ReLU(True),
        )

        self.deconv2 = nn.Sequential(
            # First convolution:
            # - Input: features from previous decoder block (deconv1)
            # - Output: new channel size (deconv_channel_num_3)
            # - Kernel=3, stride=1, padding=1 → keeps spatial resolution same
            # purpose: further transform and compress feature representation
            nn.Conv2d(self.config.deconv_channel_num_2, self.config.deconv_channel_num_3, 3, 1, 1),
            # activation (ReLU) → adds non-linearity, helps learn complex patterns
            nn.ReLU(True),
            # second convolution:
            # - keeps channel size same
            # - refines features further (deeper representation learning)
            nn.Conv2d(self.config.deconv_channel_num_3, self.config.deconv_channel_num_3, 3, 1, 1),
            # activation → improves expressiveness of features
            nn.ReLU(True),
        )

        self.deconv3 = nn.Sequential(
            # First convolution:
            # - Input: refined features from deconv2
            # - Output: same channel size (deconv_channel_num_3)
            # - Purpose: final feature refinement before prediction
            # - Kernel=3, stride=1, padding=1 → keeps spatial size unchanged
            nn.Conv2d(self.config.deconv_channel_num_3, self.config.deconv_channel_num_3, 3, 1, 1),
            # Activation → introduces non-linearity for better class separation
            nn.ReLU(True),
            # final convolution (prediction layer):
            # - converts feature maps → segmentation logits
            # - output channels = num_class
            # - each channel corresponds to one class (road, vehicle, pedestrian, etc.)
            nn.Conv2d(self.config.deconv_channel_num_3, self.num_class, 3, 1, 1),
        )

    def forward(self, x):
        # ---------------- Decoder Block 1----------------
        # refine  latent features (channel transformation) keeps spatial resolution same
        x = self.deconv1(x)
        # upsamples feature map (increase H, W) recovers spatial resolution lost in encoder
        x = F.interpolate(
        x,
        scale_factor=self.config.deconv_scale_factor_1,
        mode='bilinear',
        align_corners=False
        )
        # ---------------- Decoder Block 2----------------
        # further refine features after upsampling improves feature quality for segmentation
        x = self.deconv2(x)
        # second upsampling step brings feature map closer to original image resolution
        x = F.interpolate(
        x,
        scale_factor=self.config.deconv_scale_factor_2,
        mode='bilinear',
        align_corners=False
        )
        # ---------------- Final Prediction----------------
        # final convolution block converts features → segmentation logits (num_class channels)
        x = self.deconv3(x)
        # ---------------- Output----------------
        #  Output shape: (B, num_class, H, W) represents pixel-wise class scores
        return x

class DepthDecoder(nn.Module):
    def __init__(self, config, latent_dim=512):
        # initialize base PyTorch module (required for all models)
        super().__init__()
        # store configuration object (contains hyperparameters like channels, scale factors, etc.)
        self.config = config
        #  number of input channels (feature depth) coming from backbone typically the output of
        # encoder / fused features (e.g., 512)
        self.latent_dim = latent_dim

        self.deconv1 = nn.Sequential(
            # First convolution:
            # - Input: latent feature map from backbone (e.g., 512 channels)
            # - Output: reduced channels (deconv_channel_num_1)
            # - Kernel=3, stride=1, padding=1 → keeps spatial size unchanged
            # Purpose: start transforming high-level encoded features into depth-specific features
            nn.Conv2d(self.latent_dim, self.config.deconv_channel_num_1, 3, 1, 1),
            # actuivation -> introduces non-linearity inplace = True saves memory
            nn.ReLU(True),
            #  Second convolution:
            # - Further refines and compresses feature representation
            # - Prepares features for next decoding stage
            nn.Conv2d(self.config.deconv_channel_num_1, self.config.deconv_channel_num_2, 3, 1, 1),
            # activation improves feature expressiveness
            nn.ReLU(True),
        )

        self.deconv2 = nn.Sequential(
            # First convolution:
            # - Input: features from deconv1 (intermediate depth-aware features)
            # - Output: reduced/adjusted channels (deconv_channel_num_3)
            # - Kernel=3, stride=1, padding=1 → spatial size remains same
            # Purpose: refine and compress features further for depth estimation
            nn.Conv2d(self.config.deconv_channel_num_2, self.config.deconv_channel_num_3, 3, 1, 1),
            # Activation → introduces non-linearity, improves learning capacity
            nn.ReLU(True),
            #  Second convolution:
            # - Keeps channel size same
            # - Deepens feature representation
            # - Helps capture fine geometric details (important for depth)
            nn.Conv2d(self.config.deconv_channel_num_3, self.config.deconv_channel_num_3, 3, 1, 1),
            # Activation → enhances feature expressiveness
            nn.ReLU(True),
        )

        self.deconv3 = nn.Sequential(
            # First convolution:
            # - Input: refined features from deconv2
            # - Output: same channel size (deconv_channel_num_3)
            # - Purpose: final refinement of features before prediction
            # - Keeps spatial resolution unchanged
            nn.Conv2d(self.config.deconv_channel_num_3, self.config.deconv_channel_num_3, 3, 1, 1),
            # Activation → adds non-linearity, improves depth feature representation
            nn.ReLU(True),
            # Final output layer:
            # - Converts features → single-channel depth map
            # - Output channels = 1 (because depth is a continuous value per pixel)
            nn.Conv2d(self.config.deconv_channel_num_3, 1, 3, 1, 1),
        )

    def forward(self, x):
        # ---------------- Decoder Block 1 ----------------
        # refine latent features (convert high-level features → depth-aware features) spatial size remains unchanged
        x = self.deconv1(x)
        # upsample feature map (increase height & width) recover spatial resolution lost in encoder
        x = F.interpolate(x,scale_factor=self.config.deconv_scale_factor_1,mode='bilinear',align_corners=False)

        # ---------------- Decoder Block 2 ----------------
        # further refine features improves grometric consistency
        x = self.deconv2(x)
        # second upsampling step brings resolution closer to original input size
        x = F.interpolate(x,scale_factor=self.config.deconv_scale_factor_2,mode='bilinear',align_corners=False)

        # ---------------- Final Depth Prediction ----------------
        # convert features -> raw depth map (shape : B, 1, H, W)
        x = self.deconv3(x)

        # ---------------- Activation + Shape Adjustment  ----------------
        # 1. Sigmoid:
        # - constrains depth values to range (0, 1)
        # - useful when depth is normalized
        # 2. squeeze(1):
        # - removes channel dimension (1)
        # - (B, 1, H, W) → (B, H, W)
        x = torch.sigmoid(x).squeeze(1)
        # ----------------Output----------------
        # final output shape : (B, H, W) each pixel contains a depth value normalized between 0 and 1
        return x

# transformer module for multi-modal fusion (Image + LiDAR)
class GPT(nn.Module):
    def __init__(self, n_embd, n_head, block_exp, n_layer,img_vert_anchors, img_horz_anchors,
                 lidar_vert_anchors, lidar_horz_anchors,seq_len,embd_pdrop, attn_pdrop, resid_pdrop, config):
        # intialize base nn.Module
        super().__init__()
        # embedding dimenstion features size per token must match CNN features channels size
        self.n_embd = n_embd
        # sequence length is FIXED to 1 here
        # this indicates:
        # - no temporal sequence modeling
        # - only single-frame fusion (image + LiDAR at one timestep)
        self.seq_len = 1
        # defines spatial grid for image tokens
        self.img_vert_anchors = img_vert_anchors
        self.img_horz_anchors = img_horz_anchors
        # defines spatial grid for LiDAR BEV tokens
        self.lidar_vert_anchors = lidar_vert_anchors
        self.lidar_horz_anchors = lidar_horz_anchors
        # full configuration object used for additional parameters/settings
        self.config = config
        # ---------------- Positional Embedding----------------
        # learnable positional embedding : shape -> (1, total_tokens, embedding_dim)
        # total_tokens = (image tokens) + (LiDAR tokens) = seq_len * (img_grid_size + lidar_grid_size)
        self.pos_emb = nn.Parameter(torch.zeros(1, self.seq_len * img_vert_anchors * img_horz_anchors +
                                                self.seq_len * lidar_vert_anchors * lidar_horz_anchors,
                                                n_embd)
                                   )
        # ---------------- Dropout ----------------
        # dropout applied to input embeddings (tokens + positional embeddings) helps prevent overfitting and improves generalization
        self.drop = nn.Dropout(embd_pdrop)
        # ---------------- Transformer Block Stack Transformer ----------------
        # stack of transformer blocks (layers)
        # each Block contains:
        # - multi-head self-attention
        # - feed-forward network (MLP)
        # - residual connections + LayerNorm
        # n_layer = number of such blocks (depth of transformer)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head, block_exp, attn_pdrop, resid_pdrop) for _ in range(n_layer)])
        # ---------------- Final Normalization ----------------
        # final layer normalization stabilizes output and improves training convergence
        self.ln_f = nn.LayerNorm(n_embd)
        # ---------------- Block Size ----------------
        # defines sequence length (here = 1) used for compatibility
        self.block_size = self.seq_len
        # ---------------- Weight Initialization ----------------
        # apply custom weight initialization to all layers ensures stable training and better convergence
        self.apply(self._init_weights)

    def _init_weights(self, module):
        # ---------------- Linear Layer Initialization ----------------
        if isinstance(module, nn.Linear):
            # initialize Linear layer weights using normal (Gaussian) distribution
            # mean → typically 0
            # std  → small value (e.g., 0.02)
            # purpose:
            # - prevents exploding/vanishing gradients
            # - ensures stable transformer training
            module.weight.data.normal_(mean=self.config.gpt_linear_layer_init_mean,
                                       std=self.config.gpt_linear_layer_init_std
                                      )
            # initialize bias to zero standard practice for linear layers
            if module.bias is not None:
                module.bias.data.zero_()
        # ---------------- Layer Normalization Initialization ----------------
        elif isinstance(module, nn.LayerNorm):
            # set bias to zero -> no initial shift
            module.bias.data.zero_()
            # Initialize scaling factor (gamma) to a constant (usually 1.0)
            module.weight.data.fill_(self.config.gpt_layer_norm_init_weight)

    def forward(self, image_tensor, lidar_tensor):
        """
        Args:
            image_tensor (tensor): B*seq_len, C, H, W
            lidar_tensor (tensor): B*seq_len, C, H, W
        """
        # ---------------- Basics Shapes----------------
        # Batch Size
        bz = lidar_tensor.shape[0]
        # Spatial size of LiDAR feature map
        lidar_h, lidar_w = lidar_tensor.shape[2:4]
        # Spatial size of image feature map
        img_h, img_w = image_tensor.shape[2:4]
        # ---------------- Sequence Check ----------------
        # ensures model is operating in single-frame mode (no temporal fusion)
        assert self.seq_len == 1
        # ---------------- Image → Tokens ----------------
        # Steps:
        # 1. Reshape → separate seq_len
        # 2. Permute → move channels to last dimension
        # 3. Flatten spatial grid → tokens
        # Final shape:(B, num_image_tokens, n_embd)
        image_tensor = image_tensor.view(bz, self.seq_len, -1, img_h, img_w).permute(0, 1, 3, 4, 2).contiguous().view(bz, -1, self.n_embd)
        # ---------------- LiDAR → Tokens ----------------
        # Same process for LiDAR
        # Final shape: (B, num_lidar_tokens, n_embd)
        lidar_tensor = lidar_tensor.view(bz, self.seq_len, -1, lidar_h, lidar_w).permute(0, 1, 3, 4, 2).contiguous().view(bz, -1, self.n_embd)
        # ---------------- Concat Tokens ----------------
        # Combine image + LiDAR tokens into one sequence
        # Shape: (B, total_tokens, n_embd)
        token_embeddings = torch.cat((image_tensor, lidar_tensor), dim=1)
        # ---------------- Add Position + Dropout----------------
        # Add positional embeddings → encode spatial location
        # Apply dropout → regularization
        x = self.drop(self.pos_emb + token_embeddings)
        # ---------------- Transformers----------------
        # Multi-head attention + feed-forward layers performs cross-modal fusion (image ↔ LiDAR)
        x = self.blocks(x)  # (B, total_tokens, n_embd)
        # final normalization
        x = self.ln_f(x)  # (B, total_tokens, n_embd)
        # ---------------- Reshape Back ----------------
        # Ensure correct token structure after transformer
        x = x.view(bz,self.seq_len * self.img_vert_anchors * self.img_horz_anchors +
                   self.seq_len * self.lidar_vert_anchors * self.lidar_horz_anchors,self.n_embd
                  )
        # ---------------- Split Back To Modalities----------------
        # extract image tokens -> reshape back to feature map
        # shape : (B, C, H, W)
        image_tensor_out = x[:, :self.seq_len * self.img_vert_anchors * self.img_horz_anchors, :].contiguous().view(bz * self.seq_len, -1, img_h, img_w)
        # extract LiDAR tokens -> reshape back to features map
        lidar_tensor_out = x[:, self.seq_len * self.img_vert_anchors * self.img_horz_anchors:, :].contiguous().view(bz * self.seq_len, -1, lidar_h, lidar_w)
        # ---------------- Output ----------------
        # return fused featues maps for both modalities
        return image_tensor_out, lidar_tensor_out

class ImageCNN(nn.Module):
    """
    Encoder network for image input list.
    Args:
        architecture (string): Vision architecture to be used from the TIMM model library.
        normalize (bool): whether the input images should be normalized
    """
    def __init__(self, architecture, normalize=True, out_features=512):
        # Initialize parent class (PyTorch nn.Module)
        super().__init__()
        # Whether to normalize input images before passing through network
        self.normalize = normalize
        # Create a pretrained vision backbone using TIMM library
        self.features = timm.create_model(architecture, pretrained=True)
        # Remove the final fully connected (classification) layer because we only need feature extraction (encoder)
        self.features.fc = None
        # -----------------------------
        # Modify / Adapt Backbone Layers
        # -----------------------------
        # -> Different architectures in TIMM have different naming conventions.
        # -> below we standardize them so the rest of the code can use a common interface.
        # Initial convolution layer input processing
        self.features.conv1 = self.features.stem.conv
        # Initial batch normalization layer
        self.features.bn1 = self.features.stem.bn
        # Activation layer ReLU often already included in BN or stem
        self.features.act1 = nn.Sequential()
        # Remove max pooling layer replace with identity
        self.features.maxpool = nn.Sequential()
        # Map backbone stages to common names ResNet-style naming
        self.features.layer1 = self.features.s1
        self.features.layer2 = self.features.s2
        self.features.layer3 = self.features.s3
        self.features.layer4 = self.features.s4
        # Global average pooling to reduce spatial dimensions → (H, W) → (1, 1)
        self.features.global_pool = nn.AdaptiveAvgPool2d(output_size=1)
        # Remove classification head only need feature embeddings
        self.features.head = nn.Sequential()

    def normalize_imagenet(x):
        """ Normalize input images according to ImageNet standards.
        Args:
            x (tensor): input images
        """
        # Create a copy of input tensor revents modifying original data (important for safety in pipelines)
        x = x.clone()
        # Normalize RED channel:
        # 1. Scale pixel values from [0, 255] → [0, 1]
        # 2. Subtract mean (0.485)
        # 3. Divide by std (0.229)
        x[:, 0] = ((x[:, 0] / 255.0) - 0.485) / 0.229
        #  Normalize Green channel using ImageNet mean & std
        x[:, 1] = ((x[:, 1] / 255.0) - 0.456) / 0.224
        # Normalize Blue channel using ImageNet mean & std
        x[:, 2] = ((x[:, 2] / 255.0) - 0.406) / 0.225
        # output : normalized tensor ready for pretrained CNN models
        return x

class LidarEncoder(nn.Module):
    """
    Encoder network for LiDAR input list
    Args:
        architecture (string): Vision architecture from TIMM (e.g., ResNet, ConvNeXt)
        in_channels: number of input channels for LiDAR (not RGB!)
    """
    def __init__(self, architecture, in_channels=2, out_features=512):
        # Initialize parent class (PyTorch nn.Module)
        super().__init__()
        # ---------------- Load Backbone----------------
        # Create model from TIMM library (no pretrained weights for LiDAR)
        self._model = timm.create_model(architecture, pretrained=False)
        # Remove classification head (not needed for feature extraction)
        self._model.fc = None
        # ---------------- Standardize Module Names ----------------
        # - allows image and LiDAR encoders to share the same forward code
        #  First convolution layer
        self._model.conv1 = self._model.stem.conv
        # BatchNorm after first conv
        self._model.bn1 = self._model.stem.bn
        # Remove activation or keep identity for flexibility
        self._model.act1 = nn.Sequential()
        # Remove max pooling LiDAR spatial resolution is important
        self._model.maxpool = nn.Sequential()
        # First stage of backbone
        self._model.layer1 = self._model.s1
        #  Second stage of backbone
        self._model.layer2 = self._model.s2
        # Third stage of backbone
        self._model.layer3 = self._model.s3
        # Fourth (deepest) stage of backbone
        self._model.layer4 = self._model.s4
        # Global pooling → converts feature map to vector
        self._model.global_pool = nn.AdaptiveAvgPool2d(output_size=1)
        # Remove classification head
        self._model.head = nn.Sequential()
        # Remove classification head
        # ---------------- Modify Input Conv ----------------
        # Store original conv layer
        _tmp = self._model.conv1
        # Check if original conv had bias
        use_bias = (_tmp.bias != None)
        # Replace first conv layer:
        # - Original expects 3 channels (RGB)
        # - Now accepts LiDAR channels (e.g., 2, 4, etc.)
        self._model.conv1 = nn.Conv2d(in_channels,out_channels=_tmp.out_channels,
                                      kernel_size=_tmp.kernel_size,stride=_tmp.stride,
                                      padding=_tmp.padding,bias=use_bias)
        # ---------------- Cleanup ----------------
        # Delete old conv layer to avoid duplicate parameters
        del self._model.stem.conv
        # Clear unused GPU memory optional, but good practice)
        torch.cuda.empty_cache()
        # Delete temporary
        del _tmp

class SelfAttention(nn.Module):
    """
    A vanilla multi-head masked self-attention layer with a projection at the end.
    """
    def __init__(self, n_embd, n_head, attn_pdrop, resid_pdrop):
        # Initialize parent class (PyTorch nn.Module)
        super().__init__()
        # Ensure embedding dimension is divisible by number of heads each head will get equal sized featues chucks
        assert n_embd % n_head == 0
        # ---------------- Query, Key, Values Projections ----------------
        # - These are the core components of attention: Attention(Q, K, V) = softmax(QK^T / sqrt(d)) V
        # Projects input tokens → key vectors
        self.key = nn.Linear(n_embd, n_embd)
        # Projects input tokens → query vectors
        self.query = nn.Linear(n_embd, n_embd)
        # Projects input tokens → value vectors
        self.value = nn.Linear(n_embd, n_embd)
        # ---------------- Dropout(Regularization) ----------------
        # Dropout applied on attention weights prevents over-reliance on specific tokens
        self.attn_drop = nn.Dropout(attn_pdrop)
        #  Dropout applied after output projection (residual path) improves generalization
        self.resid_drop = nn.Dropout(resid_pdrop)
        # ---------------- Output Projection ----------------
        # Combines outputs from all heads maps concatenated multi-head outputs → final embedding
        self.proj = nn.Linear(n_embd, n_embd)
        # ---------------- Number of Heads----------------
        # Number of parallel attention heads each head learns different relationships
        self.n_head = n_head
        # ---------------- Attention Map Storage ----------------
        # Stores attention weights
        self.attn_map = None
    def forward(self, x):
        #  B = batch size
        # T = number of tokens (image + LiDAR tokens)
        # C = embedding dimension
        B, T, C = x.size()
        # ---------------- Create  Q, K, V ----------------
        # Key projection: (B, T, C) → (B, T, n_head, head_dim) → (B, n_head, T, head_dim)
        k = self.key(x).view(B, T, self.n_head, C // self.n_head).transpose(1, 2)
        # Query projection (same reshaping)
        q = self.query(x).view(B, T, self.n_head, C // self.n_head).transpose(1, 2)
        # Value projection (same reshaping)
        # now shape for all : (B, n_head, T, head_dim)
        v = self.value(x).view(B, T, self.n_head, C // self.n_head).transpose(1, 2)
        # ---------------- Attention Scores ----------------
        #  Matrix multiplication:  (B, nh, T, hs) × (B, nh, hs, T) → (B, nh, T, T)
        #  Computes similarity between every pair of tokens: "How much should token i attend to token j?"
        #  Scaling by sqrt(head_dim): Prevents large values → stabilizes softmax
        att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
        # ---------------- Softmax ----------------
        # convert scores -> probabilities
        #  Each row sums to 1 (attention distribution)
        att = F.softmax(att, dim=-1)
        # ---------------- Store Attention Map Store ----------------
        #  Save attention weights for visualization/debugging
        # detach → remove from computation graph
        # cpu → move to CPU
        # numpy → convert to array
        self.attn_map = att.detach().cpu().numpy()
        # ---------------- Dropout on Attention----------------
        # Regularization → prevents overfitting
        att = self.attn_drop(att)
        # ---------------- Apply Attention ----------------
        # Each token becomes a weighted sum of all other tokens this is where "information mixing" happens
        # (B, nh, T, T) × (B, nh, T, hs) → (B, nh, T, hs)
        y = att @ v
        # ---------------- Merge Heads ----------------
        # Combine all heads into single embedding
        # (B, nh, T, hs) → (B, T, nh, hs) → (B, T, C)
        y = y.transpose(1, 2).contiguous().view(B, T, C)
        # ---------------- Output Projection ----------------
        # Linear projection → mixes information from all heads
        # Dropout → regularization
        y = self.resid_drop(self.proj(y))
        # Output shape: (B, T, C)
        return y

class Block(nn.Module):
    """ an unassuming Transformer block """
    def __init__(self, n_embd, n_head, block_exp, attn_pdrop, resid_pdrop):
        # Initialize parent class (PyTorch nn.Module)
        super().__init__()
        # LayerNorm before attention (Pre-Norm)
        # Stabilizes training and improves gradient flow
        self.ln1 = nn.LayerNorm(n_embd)
        #  LayerNorm before MLP (feed-forward network)
        self.ln2 = nn.LayerNorm(n_embd)
        # Multi-head self-attention module
        # Learns relationships between tokens (image ↔ LiDAR)
        self.attn = SelfAttention(n_embd, n_head, attn_pdrop, resid_pdrop)
        self.mlp = nn.Sequential(
            # First linear layer:
            # Expands embedding dimension (e.g., 512 → 2048)
            # Allows richer feature representation
            nn.Linear(n_embd, block_exp * n_embd),
            # Activation function
            # ReLU is faster than GELU (used in original GPT)
            nn.ReLU(True),  # changed from GELU
            # Projects back to original embedding size
            nn.Linear(block_exp * n_embd, n_embd),
            # Dropout for regularization
            nn.Dropout(resid_pdrop),
        )

    def forward(self, x):
        # ---------------- Attention + Residual ----------------
        # Step 1: Apply LayerNorm to input (Pre-Norm)
        # Step 2: Pass normalized input through self-attention
        # Step 3: Add residual connection (skip connection)
        # Why residual?
        # - Preserves original information
        # - Helps gradient flow (avoids vanishing gradients)
        # - Makes deep transformers stable
        x = x + self.attn(self.ln1(x))
        # ---------------- MLP + RESIDUAL ----------------
        # Step 1: Apply LayerNorm again
        # Step 2: Pass through feed-forward network (MLP)
        # Step 3: Add residual connection
        # MLP processes each token independently adds non-linearity and richer feature representation
        x = x + self.mlp(self.ln2(x))
        # Output shape: (B, T, C)
        # Tokens now contain richer, context-aware information
        return x

